/*global define */

define({
    BUTTON_CANCEL:                      "Cancel",
    BUTTON_CHANGELOG:                   "Show changelog",
    BUTTON_CLOSE:                       "Close",
    BUTTON_CLOSE_NOT_MODIFIED:          "Close not modified",
    BUTTON_COMMIT:                      "Commit",
    BUTTON_DEFAULTS:                    "Restore defaults",
    BUTTON_OK:                          "OK",
    BUTTON_PULL:                        "Git Pull",
    BUTTON_PUSH:                        "Git Push",
    BUTTON_RESET:                       "Reset index",
    BUTTON_SAVE:                        "Save",
    CHANGELOG:                          "Changelog",
    CHECK_GIT_SETTINGS:                 "Check Git settings",
    COMMIT_MESSAGE_PLACEHOLDER:         "Enter commit message here\u2026",
    DELETE_FILE:                        "Delete file",
    DIFF:                               "Diff",
    EXTENSION_WAS_UPDATED_TITLE:        "The extension was updated to {0}",
    FEATURE_SETTINGS:                   "Feature settings",
    FILE_DELETED:                       "Deleted",
    FILE_MODIFIED:                      "Modified",
    FILE_NEWFILE:                       "New file",
    FILE_STAGED:                        "Staged",
    FILE_UNTRACKED:                     "Untracked",
    FILE_RENAMED:                       "Renamed",
    FOR_WINDOWS_USERS:                  "For Windows users",
    GIT_COMMIT:                         "Git commit\u2026",
    GIT_DIFF:                           "Git diff &mdash;",
    GIT_IS_IN_PATH:                     "Git can be called from anywhere (is in system path, might not work on Mac)",
    GIT_PULL_RESPONSE:                  "Git Pull response",
    GIT_PUSH_RESPONSE:                  "Git Push response",
    GIT_SETTINGS:                       "Git Settings\u2026",
    LOADING:                            "Loading\u2026",
    NOTHING_TO_COMMIT:                  "Nothing to commit, working directory clean.",
    PATH_TO_GIT_EXECUTABLE:             "Path to Git executable",
    PATH_TO_GIT_MSYSGIT:                "Path to msysgit folder",
    PANEL_COMMAND:                      "Git",
    Q_DELETE_FILE:                      "Are you sure you wish to delete the file {0}?",
    Q_RESTART_BRACKETS:                 "Do you wish to restart Brackets to apply new settings?",
    Q_UNDO_CHANGES:                     "Reset changes to file {0}?",
    RESTART:                            "Restart",
    STRIP_WHITESPACE_FROM_COMMITS:      "Strip trailing whitespace from commits",
    UNDO_CHANGES:                       "Undo changes",
    USING_GIT_VERSION:                  "Git version"
});
