/*global define */

define({
    ADD_ENDLINE_TO_THE_END_OF_FILE:     "Add endline at the end of file",
    ADD_TO_GITIGNORE:                   "Add to .gitignore",
    AMEND_COMMIT:                       "Amend last commit",
    AMEND_COMMIT_FORBIDDEN:             "Cannot amend commit when there are no unpushed commits",
    REMOVE_FROM_GITIGNORE:              "Remove from .gitignore",
    BRACKETS_GIT_ERROR:                 "Brackets Git encountered an error\u2026",
    BRANCH_NAME:                        "Branch name",
    TOOLTIP_BUG:                        "Report bug",
    BUTTON_CANCEL:                      "Cancel",
    BUTTON_CHANGELOG:                   "Show changelog",
    BUTTON_CLOSE:                       "Close",
    BUTTON_CLOSE_NOT_MODIFIED:          "Close not modified",
    BUTTON_COMMIT:                      "Commit",
    BUTTON_DEFAULTS:                    "Restore defaults",
    BUTTON_HIDE_UNTRACKED:              "Hide untracked",
    BUTTON_SHOW_UNTRACKED:              "Show untracked",
    BUTTON_INIT:                        "Init",
    BUTTON_OK:                          "OK",
    TOOLTIP_PULL:                       "Git Pull",
    TOOLTIP_PUSH:                       "Git Push",
    TOOLTIP_OPEN_BASH:                  "Open Bash console",
    BUTTON_REPORT:                      "Report",
    BUTTON_REFRESH_PANEL:               "Refresh panel",
    BUTTON_SAVE:                        "Save",
    CHANGELOG:                          "Changelog",
    CHECK_GIT_SETTINGS:                 "Check Git settings",
    COMMIT_MESSAGE_PLACEHOLDER:         "Enter commit message here\u2026",
    CREATE_NEW_BRANCH:                  "Create new branch\u2026",
    DELETE_FILE:                        "Delete file",
    DIFF:                               "Diff",
    EXTENSION_WAS_UPDATED_TITLE:        "The extension was updated to {0}",
    FEATURE_SETTINGS:                   "Feature settings",
    FILE_DELETED:                       "Deleted",
    FILE_MODIFIED:                      "Modified",
    FILE_NEWFILE:                       "New file",
    FILE_STAGED:                        "Staged",
    FILE_UNTRACKED:                     "Untracked",
    FILE_RENAMED:                       "Renamed",
    FOR_WINDOWS_USERS:                  "For Windows users",
    GIT_COMMIT:                         "Git commit\u2026",
    GIT_DIFF:                           "Git diff &mdash;",
    GIT_IS_IN_PATH:                     "Git can be called from anywhere (is in system path, might not work on Mac)",
    GIT_PULL_RESPONSE:                  "Git Pull response",
    GIT_PUSH_RESPONSE:                  "Git Push response",
    GIT_SETTINGS:                       "Git Settings\u2026",
    LOADING:                            "Loading\u2026",
    NOTHING_TO_COMMIT:                  "Nothing to commit, working directory clean.",
    PATH_TO_GIT_EXECUTABLE:             "Path to Git executable",
    PATH_TO_GIT_MSYSGIT:                "Path to msysgit folder",
    PANEL_COMMAND:                      "Git",
    PANEL_SHORTCUT:                     "Toggle panel keyboard shortcut",
    Q_DELETE_FILE:                      "Are you sure you wish to delete the file {0}?",
    Q_RESTART_BRACKETS:                 "Do you wish to restart Brackets to apply new settings?",
    Q_UNDO_CHANGES:                     "Reset changes to file {0}?",
    RESTART:                            "Restart",
    SET_ORIGIN_URL:                     "Set origin URL",
    STRIP_WHITESPACE_FROM_COMMITS:      "Strip trailing whitespace from commits",
    UNDO_CHANGES:                       "Undo changes",
    URL:                                "URL",
    USE_GIT_GUTTER:                     "Use Git gutter marks",
    USING_GIT_VERSION:                  "Git version"
});
