/*jshint maxlen:false */

define({
    ADD_ENDLINE_TO_THE_END_OF_FILE:     "Aggiungi fine riga alla fine del file",
    ADD_TO_GITIGNORE:                   "Aggiungi al .gitignore",
    AGREE_TO_STORE_PASSWORDS:           "Accetto che le password siano salvate in chiaro sul mio computer",
    AMEND_COMMIT:                       "Correggi l’ultimo commit",
    AMEND_COMMIT_FORBIDDEN:             "Impossibile correggere un commit quando non ce ne sono di non inviati",
    AUTHOR:                             "Autore",
    AUTHORS_OF:                         "Autori di",
    BASH_NOT_AVAILABLE:                 "Bash non è disponibile o non è correttamente configurato",
    BASIC_CONFIGURATION:                "Configurazione di base",
    BRACKETS_GIT_ERROR:                 "Brackets Git ha rilevato un errore\u2026",
    BRANCH_NAME:                        "Nome branch",
    BUTTON_CANCEL:                      "Annulla",
    BUTTON_CHANGELOG:                   "Mostra il changelog",
    BUTTON_CLOSE:                       "Chiudi",
    BUTTON_DEFAULTS:                    "Ripristina predefiniti",
    BUTTON_OK:                          "OK",
    BUTTON_REPORT:                      "Segnala",
    BUTTON_SAVE:                        "Salva",
    BUTTON_COMMIT:                      "Commit",
    BUTTON_INIT:                        "Inizializza",
    BUTTON_CLONE:                       "Clona",
    CHANGELOG:                          "Changelog",
    CHANGE_USER_NAME:                   "Cambia il nome utente di Git",
    CHANGE_USER_EMAIL:                  "Cambia l’indirizzo email di Git",
    CHECK_GIT_SETTINGS:                 "Controlla le impostazioni di Git",
    COMMAND_ARGUMENTS:                  "Argomenti del comando",
    COMMIT_ALL_SHORTCUT:                "Commit di tutti i file",
    COMMIT_CURRENT_SHORTCUT:            "Commit del file corrente",
    COMMIT_MESSAGE_PLACEHOLDER:         "Inserisci qui il messaggio di commit\u2026",
    CLONE_REPOSITORY:                   "Clona il repository",
    CREATE_NEW_BRANCH:                  "Crea un nuovo branch\u2026",
    CREATE_NEW_REMOTE:                  "Crea un nuovo remote\u2026",
    CUSTOM_TERMINAL_COMMAND:            "Comando del terminale personalizzato (esempio: gnome-terminal o il percorso completo all’eseguibile)",
    CUSTOM_TERMINAL_COMMAND_HINT:       "Argomenti di esempio: --window --working-directory=$1<br>$1 negli argomenti verà rimpiazzato con il percorso della directory del progetto.",
    DEBUG:                              "Debug",
    DEBUG_MODE_SETTING:                 "Modalità di debug &mdash; Lasciarla disattivata a meno che non si debba trovare un problema. Tutte le comunicazioni con Git verranno inviate alla console di Brackets!",
    DELETE_FILE:                        "Cancella il file",
    DELETE_REMOTE:                      "Cancella il remote",
    DELETE_REMOTE_NAME:                 "Vuoi veramente eliminare il remote \"{0}\"?",
    DIFF:                               "Differenze",
    DIFF_FAILED_SEE_FILES:              "Git non è riuscito a fornire le differenze. Questa è la lista dei file staged su cui verrà effettuato il commit:",
    ENTER_PASSWORD:                     "Inserisci password",
    ENTER_USERNAME:                     "Inserisci nome utente",
    ENTER_REMOTE_GIT_URL:               "Inserisci l’indirizzo Git del repository che si vuole clonare",
    ENTER_REMOTE_NAME:                  "Inserisci il nome del nuovo remote",
    ENTER_REMOTE_URL:                   "Inserisci l’URL del nuovo remote",
    ERROR_TERMINAL_NOT_FOUND:           "Il terminale non è stato trovato per il tuo sistema operativo, puoi definire un comando da terminale personalizzato nelle impostazioni",
    EXTENDED_COMMIT_MESSAGE:            "Forma estesa",
    EXTENSION_WAS_UPDATED_TITLE:        "L’estensione è stata aggiornata alla versione {0}",
    ENTER_NEW_USER_NAME:                "Inserisci il nome utente",
    ENTER_NEW_USER_EMAIL:               "Inserisci l’indirizzo email",
    FEATURES:                           "Funzionalità",
    FILE_DELETED:                       "Cancellato",
    FILE_MODIFIED:                      "Modificato",
    FILE_NEWFILE:                       "Nuovo file",
    FILE_RENAMED:                       "Rinominato",
    FILE_STAGED:                        "Staged",
    FILE_UNTRACKED:                     "Non monitorato",
    FILE_UNMERGED:                      "Non mergato",
    FOR_MAC_LINUX_USERS:                "Per utenti Mac/Linux",
    FOR_WINDOWS_USERS:                  "Per utenti Windows",
    GIT_COMMIT:                         "Git commit\u2026",
    GIT_CONFIGURATION:                  "Configurazione di Git",
    GIT_DIFF:                           "Git diff &mdash;",
    GIT_IS_IN_PATH:                     "Git può essere chiamato da qualunque punto (è nella cartella di sistema, potrebbe non funzionare su Mac)",
    GIT_PULL_RESPONSE:                  "Risposta del Git Pull",
    GIT_PUSH_RESPONSE:                  "Risposta del Git Push",
    GIT_SETTINGS:                       "Impostazioni di Git\u2026",
    GOTO_PREVIOUS_GIT_CHANGE:           "Vai alla modifica di Git precedente",
    GOTO_NEXT_GIT_CHANGE:               "Vai alla modifica di git successiva",
    LAUNCH_BASH_SHORTCUT:               "Scorciatoia del terminale bash",
    LOADING:                            "Caricamento\u2026",
    LINES:                              "Linee",
    _LINES:                             "linee",
    LIST_MODIFIED_FILES:                "File modificati",
    MARK_MODIFIED_FILES_IN_TREE:        "Evidenzia i file modificati nell’elenco a sinistra",
    NOTHING_TO_COMMIT:                  "Nessun file su cui effettuare il commit, la cartella è pulita.",
    PANEL_COMMAND:                      "Mostra il pannello di Git",
    PANEL_SHORTCUT:                     "Mostra/nascondi pannello",
    PASSWORDS:                          "Password",
    PATH_TO_GIT_EXECUTABLE:             "Percorso dell’eseguibile Git",
    PATH_TO_GIT_MSYSGIT:                "Percorso della cartella msysgit",
    PULL_SHORTCUT:                      "Scarica dal repository remoto",
    PUSH_SHORTCUT:                      "Carica sul repository remoto",
    Q_DELETE_FILE:                      "Sei sicuro di voler cancellare il file <span class='dialog-filename'>{0}</span>?",
    Q_RESTART_BRACKETS:                 "Desideri riavviare Brackets per applicare le nuove impostazioni?",
    Q_UNDO_CHANGES:                     "Revertire le modifiche al file <span class='dialog-filename'>{0}</span>?",
    REMOVE_FROM_GITIGNORE:              "Rimuovi dal .gitignore",
    RESTART:                            "Riavvia",
    SAVE_PASSWORD_QUESTION:             "Ricordare nome utente/password?",
    SET_ORIGIN_URL:                     "Imposta URL di origine",
    SHORTCUTS:                          "Scorciatoie",
    SHORTCUTS_HINT:                     "Separare i tasti con un trattino, come così: Ctrl-Alt-G<br>Puoi usare gli identificativi inglesi dei tasti Ctrl, Cmd (per Mac), Alt e Shift.",
    SHOW_BASH_TERMINAL_BUTTON:          "Visualizza il bottone del terminale bash nel pannello",
    SHOW_REPORT_BUG_BUTTON:             "Visualizza il bottone per segnalare un bug nel pannello",
    STRIP_WHITESPACE_FROM_COMMITS:      "Rimuovi spazi alla fine dei file dai commit",
    TOOLTIP_BUG:                        "Segnala bug",
    TOOLTIP_OPEN_BASH:                  "Apri la console Bash",
    TOOLTIP_PULL:                       "Git Pull",
    TOOLTIP_PUSH:                       "Git Push",
    TOOLTIP_CLOSE_NOT_MODIFIED:         "Chiudi i file non modificati su Git",
    TOOLTIP_INIT:                       "inizializza il repository",
    TOOLTIP_CLONE:                      "Clona un repository esistente",
    TOOLTIP_COMMIT:                     "Commit i file selezionati",
    TOOLTIP_SHOW_UNTRACKED:             "Mostra file non monitorati",
    TOOLTIP_HIDE_UNTRACKED:             "Nascondi file non monitorati",
    TOOLTIP_REFRESH_PANEL:              "Aggiorna pannello",
    TOOLTIP_HIDE_HISTORY:               "Nascondi la storia",
    TOOLTIP_SHOW_HISTORY:               "Mostra la storia",
    TOOLTIP_PICK_REMOTE:                "Seleziona il repository remoto preferito",
    TOOLTIP_MORE:                       "Più opzioni\u2026",
    UNDO_CHANGES:                       "Annulla modifiche",
    URL:                                "URL",
    USE_CODE_INSPECTION:                "Utilizza l’ispettore del codice",
    USE_GIT_GUTTER:                     "Usa la guida laterale di Git per mostrare gli indicatori",
    USING_GIT_VERSION:                  "Versione di Git",
    UNDO_LAST_LOCAL_COMMIT:             "Annulla l’ultimo commit locale (non caricato)",
    VIEW_AUTHORS_SELECTION:             "Mostra gli autori della selezione",
    VIEW_AUTHORS_FILE:                  "Mostra gli autori del file"
});
