/*jshint maxlen:false */
/*global define */

define({
    ADD_ENDLINE_TO_THE_END_OF_FILE:     "Aggiungi fine riga alla fine del file",
    ADD_TO_GITIGNORE:                   "Aggiungi a .gitignore",
    AMEND_COMMIT:                       "COrreggi ultimo commit",
    AMEND_COMMIT_FORBIDDEN:             "Impossibile correggere un commit quando non ve ne sono non inviati (unpushed)",
    BASH_NOT_AVAILABLE:                 "Bash non è disponibile o non è correttamente configurato",
    BASIC_CONFIGURATION:                "Configurazione base",
    BRACKETS_GIT_ERROR:                 "Brackets Git ha rilevato un errore\u2026",
    BRANCH_NAME:                        "Nome ramo (branch)",
    BUTTON_CANCEL:                      "Annulla",
    BUTTON_CHANGELOG:                   "Mostra changelog",
    BUTTON_CLOSE:                       "Chiudi",
    BUTTON_DEFAULTS:                    "Ripristina predefiniti",
    BUTTON_OK:                          "OK",
    BUTTON_REPORT:                      "Segnala",
    BUTTON_SAVE:                        "Salva",
    BUTTON_COMMIT:                      "Commit",
    BUTTON_INIT:                        "Inizializza",
    CHANGELOG:                          "Changelog",
    CHECK_GIT_SETTINGS:                 "Controlla impostazioni Git",
    COMMIT_ALL_SHORTCUT:                "Commit tutti i file",
    COMMIT_CURRENT_SHORTCUT:            "Commit il file corrente",
    COMMIT_MESSAGE_PLACEHOLDER:         "Inserisci il messaggio di commit qui\u2026",
    CREATE_NEW_BRANCH:                  "Crea un nuovo ramo (branch)\u2026",
    CUSTOM_TERMINAL_COMMAND:            "Comando da terminale personalizzato (esempio: gnome-terminal --window --working-directory=$1)",
    DELETE_FILE:                        "Cancella file",
    DIFF:                               "Diff",
    ENTER_PASSWORD:                     "Inserisci password",
    ENTER_USERNAME:                     "Inserisci nome utente",
    ERROR_TERMINAL_NOT_FOUND:           "Il terminale non è stato trovato per il tuo sistema operativo, puoi definire un comando da terminale personalizzato nelle impostazioni",
    EXTENSION_WAS_UPDATED_TITLE:        "L’estensione è stata aggiornata alla versione {0}",
    FEATURES:                           "Funzionalità",
    FILE_DELETED:                       "Cancellato",
    FILE_MODIFIED:                      "Modificato",
    FILE_NEWFILE:                       "Nuovo file",
    FILE_RENAMED:                       "Rinominato",
    FILE_STAGED:                        "Staged",
    FILE_UNTRACKED:                     "Non monitorato",
    FOR_MAC_LINUX_USERS:                "Per utenti Mac/Linux",
    FOR_WINDOWS_USERS:                  "Per utenti Windows",
    GIT_COMMIT:                         "Git commit\u2026",
    GIT_DIFF:                           "Git diff &mdash;",
    GIT_IS_IN_PATH:                     "Git può essere chiamato da qualunque punto (è nella cartella di sistema, potrebbe non funzionare su Mac)",
    GIT_PULL_RESPONSE:                  "Risposta del Git Pull",
    GIT_PUSH_RESPONSE:                  "Risposta del Git Push",
    GIT_SETTINGS:                       "Impostazioni di Git\u2026",
    LOADING:                            "Caricamento\u2026",
    MARK_MODIFIED_FILES_IN_TREE:        "Evidenzia i file modificati nell’elenco a sinistra",
    NOTHING_TO_COMMIT:                  "Niente necessita un commit, la cartella è pulita.",
    PANEL_COMMAND:                      "Git",
    PANEL_SHORTCUT:                     "Mostra/nascondi pannello",
    PATH_TO_GIT_EXECUTABLE:             "Percorso dell’eseguibile Git",
    PATH_TO_GIT_MSYSGIT:                "Percorso della cartella msysgit",
    Q_DELETE_FILE:                      "Sei sicuro di voler cancellare il file {0}?",
    Q_RESTART_BRACKETS:                 "Desideri riavviare Brackets per applicare le nuove impostazioni?",
    Q_UNDO_CHANGES:                     "Revertire le modifiche al file {0}?",
    REMOVE_FROM_GITIGNORE:              "Rimuovi da .gitignore",
    RESTART:                            "Riavvia",
    SAVE_PASSWORD_QUESTION:             "Ricordare nome utente/password?",
    SET_ORIGIN_URL:                     "Imposta URL di origine",
    STRIP_WHITESPACE_FROM_COMMITS:      "Rimuovi spazi alla fine dei file dai commit",
    TOOLTIP_BUG:                        "Segnala bug",
    TOOLTIP_OPEN_BASH:                  "Apri la console Bash",
    TOOLTIP_PULL:                       "Git Pull",
    TOOLTIP_PUSH:                       "Git Push",
    TOOLTIP_CLOSE_NOT_MODIFIED:         "Chiudi file non modificati",
    TOOLTIP_INIT:                       "inizializza il repository",
    TOOLTIP_COMMIT:                     "Commit i file selezionati",
    TOOLTIP_SHOW_UNTRACKED:             "Mostra file non monitorati",
    TOOLTIP_HIDE_UNTRACKED:             "Nascondi file non monitorati",
    TOOLTIP_REFRESH_PANEL:              "Aggiorna pannello",
    UNDO_CHANGES:                       "Annulla modifiche",
    URL:                                "URL",
    USE_GIT_GUTTER:                     "Usa la guida laterale di Git per mostrare gli indicatori",
    USING_GIT_VERSION:                  "Versione di Git"
});
