/*jshint maxlen:false */

define({
    ADD_ENDLINE_TO_THE_END_OF_FILE:     "Ajouter un saut de ligne à la fin du fichier",
    ADD_TO_GITIGNORE:                   "Ajouter au .gitignore",
    AGREE_TO_STORE_PASSWORDS:           "Je comprends que les mots de passe sont stockés en texte clair sur mon ordinateur",
    AMEND_COMMIT:                       "Modifier le dernier commit",
    AMEND_COMMIT_FORBIDDEN:             "Impossible de modifier le commit quand il n'y a pas de commit en attente de push",
    AUTHOR:                             "Auteur",
    AUTHORS_OF:                         "Auteurs de",
    BASH_NOT_AVAILABLE:                 "Bash n'est pas disponible ou n'est pas proprement configuré",
    BASIC_CONFIGURATION:                "Configuration basique",
    BRACKETS_GIT_ERROR:                 "Brackets Git a rencontré une erreur\u2026",
    BRANCH_NAME:                        "Nom de la branche",
    BUTTON_CANCEL:                      "Annuler",
    BUTTON_CHANGELOG:                   "Voir le journal des changements",
    BUTTON_CLOSE:                       "Fermer",
    BUTTON_DEFAULTS:                    "Restaurer les paramètres par défaut",
    BUTTON_OK:                          "OK",
    BUTTON_REPORT:                      "Signaler",
    BUTTON_SAVE:                        "Enregistrer",
    BUTTON_COMMIT:                      "Commiter",
    BUTTON_INIT:                        "Initialiser",
    BUTTON_CLONE:                       "Cloner",
    CHANGELOG:                          "Journal des changements",
    CHANGE_USER_NAME:                   "Changer le nom d'utilisateur git",
    CHANGE_USER_EMAIL:                  "Changer l'adresse email git",
    CHECK_GIT_SETTINGS:                 "Vérifier les paramètres Git",
    CODE_INSPECTION_PROBLEMS:           "Problèmes lors de l'inspection du code :",
    COMMAND_ARGUMENTS:                  "Arguments de la commande",
    COMMIT:                             "Commiter",
    COMMIT_ALL_SHORTCUT:                "Commiter tous les fichiers",
    COMMIT_CURRENT_SHORTCUT:            "Commiter le fichier actif",
    COMMIT_MESSAGE_PLACEHOLDER:         "Entrez le message de commit\u2026",
    CLONE_REPOSITORY:                   "Cloner le Dépôt",
    CREATE_NEW_BRANCH:                  "Créer une nouvelle branche\u2026",
    CREATE_NEW_REMOTE:                  "Créer un nouveau Dépôt distant\u2026",
    CREATE_NEW_GITFTP_REMOTE:           "Créer un nouveau Git-FTP distant\u2026",
    CUSTOM_TERMINAL_COMMAND:            "Commande terminal personnalisée (exemple : gnome-terminal ou le lien complet vers l'exécutable)",
    CUSTOM_TERMINAL_COMMAND_HINT:       "Arguments exemple : --window --working-directory=$1<br>$1 dans les arguments sera remplacé par le dossier du projet actuel.",
    DATE_FORMAT:                        "DD-MM-YYYY HH:mm:ss",
    DATE_MODE_0:                        "Formaté en suivant le format de date local",
    DATE_MODE_1:                        "Temps relatif",
    DATE_MODE_2:                        "Mode intelligent (relatif/formaté)",
    DATE_MODE_3:                        "Formaté suivant votre propre format",
    DATE_MODE_4:                        "Date Git originale",
    DEBUG:                              "Debug",
    DEBUG_MODE_SETTING:                 "Mode DEBUG mdash; Laissez ceci désactivé sauf si vous avez un problème avec l'extension. Toute les communications Git seront redirigées vers la console de Brackets !",
    DELETE_FILE:                        "Supprimer le fichier",
    DELETE_REMOTE:                      "Supprimer le Dépôt distant",
    DELETE_REMOTE_NAME:                 "Êtes-vous sûr de vouloir supprimer le Dépôt distant \"{0}\"?",
    DELETE_LOCAL_BRANCH:                "Supprimer la branche locale",
    DELETE_LOCAL_BRANCH_NAME:           "Êtes-vous sûr de vouloir supprimer la branche locale \"{0}\"?",
    DIFF:                               "Diff",
    DIFF_FAILED_SEE_FILES:              "Git diff n'a pas réussi à fournir de résultat diff. Ceci est la liste des fichiers en attente d'être commités :",
    ENTER_PASSWORD:                     "Entrez le mot de passe :",
    ENTER_USERNAME:                     "Entrez le nom d'utilisateur :",
    ENTER_REMOTE_GIT_URL:               "Entrez l'adresse Git du Dépôt à cloner :",
    ENTER_REMOTE_NAME:                  "Entrez le nom du nouveau Dépôt distant :",
    ENTER_GITFTP_REMOTE_NAME:           "Entrez le nom du nouveau Git-FTP distant :",
    ENTER_REMOTE_URL:                   "Entrez l'adresse du nouveau Dépôt distant :",
    ENTER_GITFTP_REMOTE_URL:            "Entrez l'adresse FTP du nouveau Git-FTP distant en spécifiant le nom d'utilisateur et le mot de passe :",
    ERROR_TERMINAL_NOT_FOUND:           "Terminal n'a pas été trouvé sur votre OS, vous pouvez définir une commande terminal personnalisée dans les paramètres",
    EXTENDED_COMMIT_MESSAGE:            "ETENDU",
    EXTENSION_WAS_UPDATED_TITLE:        "L'extension a été mise à jour en {0}",
    ENTER_NEW_USER_NAME:                "Entrez le nom d'utilisateur",
    ENTER_NEW_USER_EMAIL:               "Entrez l'adresse email",
    FEATURES:                           "Fonctionnalités",
    FILE_DELETED:                       "Supprimé",
    FILE_MODIFIED:                      "Modifié",
    FILE_NEWFILE:                       "Nouveau fichier",
    FILE_RENAMED:                       "Renommé",
    FILE_STAGED:                        "Suivi",
    FILE_UNTRACKED:                     "Non suivi",
    FILE_UNMERGED:                      "Non fusionné",
    FOR_MAC_LINUX_USERS:                "Pour les utilisateurs Mac/Linux",
    FOR_WINDOWS_USERS:                  "Pour les utilisateurs Windows",
    GIT_COMMIT:                         "Git commit\u2026",
    GIT_CONFIGURATION:                  "Configuration Git",
    GIT_DIFF:                           "Git diff &mdash;",
    GIT_IS_IN_PATH:                     "Git peut être appelé de n'importe ou (il est dans le chemin système, peut ne pas fonctionner sous Mac)",
    GIT_PULL_RESPONSE:                  "Réponse Git Pull (Récupérer)",
    GIT_PUSH_RESPONSE:                  "Réponse Git Push (Pousser)",
    GITFTP_PUSH_RESPONSE:               "Réponse Git-FTP Push (Pousser)",
    GIT_SETTINGS:                       "Paramètres Git\u2026",
    GIT_REMOTES:                        "Dépôts distants Git",
    GITFTP_REMOTES:                     "Dépôts distants Git-FTP",
    GOTO_PREVIOUS_GIT_CHANGE:           "Aller au changement Git précédent",
    GOTO_NEXT_GIT_CHANGE:               "Aller au changement Git suivant",
    INIT_GITFTP_REMOTE_NAME:            "Initialiser le dépot distant Git-FTP \"{0}\"?",
    LAUNCH_BASH_SHORTCUT:               "Raccourci Bash/Terminal",
    LOADING:                            "Chargement\u2026",
    LINES:                              "Lignes",
    _LINES:                             "lignes",
    LIST_MODIFIED_FILES:                "Fichiers modifiés",
    MARK_MODIFIED_FILES_IN_TREE:        "Marquer les fichiers modifiés dans l'arborescence",
    MERGE_BRANCH:                       "Fusionner la branche",
    MERGE_RESULT:                       "Résultat de la fusion",
    NOTHING_TO_COMMIT:                  "Rien à commiter, répertoire de travail vide.",
    ORIGIN_BRANCH:                      "Branche d'origine",
    PANEL_COMMAND:                      "Voir le panneau Git",
    PANEL_SHORTCUT:                     "Basculer le panneau",
    PASSWORDS:                          "Mots de passe",
    PATH_TO_GIT_EXECUTABLE:             "Chemin de l'exécutable Git",
    PATH_TO_GIT_MSYSGIT:                "Chemin du dossier msysgit",
    PULL_SHORTCUT:                      "Récupérer (Pull) depuis le dépôt distant",
    PUSH_SHORTCUT:                      "Pousser (Push) sur le dépôt distant",
    Q_DELETE_FILE:                      "Êtes-vous sûr de vouloir supprimer le fichier <span class='dialog-filename'>{0}</span> ?",
    Q_RESTART_BRACKETS:                 "Souhaitez-vous redémarrer Brackets pour appliquer les nouveaux paramètres ?",
    Q_UNDO_CHANGES:                     "Annuler les modifications du fichier <span class='dialog-filename'>{0}</span> ?",
    REMOVE_FROM_GITIGNORE:              "Supprimer du .gitignore",
    RESTART:                            "Redémarrer",
    SAVE_PASSWORD_QUESTION:             "Enregistrer nom d'utilisateur/mot de passe ?",
    SET_ORIGIN_URL:                     "Définir l'adresse d'origine",
    SHORTCUTS:                          "Raccourcis",
    SHORTCUTS_HINT:                     "Touches séparées par un tiret, comme ceci : Ctrl-Alt-G<br>Vous pouvez utiliser les identifiants anglais des touches comme Ctrl, Cmd (Mac), Alt et Shift.",
    SHOW_BASH_TERMINAL_BUTTON:          "Afficher le bouton Bash/Terminal dans le panneau",
    SHOWN_DATE_FORMAT:                  "Format des dates de commit dans l'historique",
    SHOW_REPORT_BUG_BUTTON:             "Afficher le bouton de signalement de bugs dans le panneau",
    STRIP_WHITESPACE_FROM_COMMITS:      "Retirer les espaces vides de queue lors des commits",
    TARGET_BRANCH:                      "Branche cible",
    TOOLTIP_BUG:                        "Signaler un bug",
    TOOLTIP_OPEN_BASH:                  "Ouvrir la console Bash/Terminal",
    TOOLTIP_PULL:                       "Git Pull (Récupérer)",
    TOOLTIP_PUSH:                       "Git Push (Pousser)",
    TOOLTIP_GITPUSH:                    "Git-FTP Push (Pousser)",
    TOOLTIP_CLOSE_NOT_MODIFIED:         "Fermer les fichiers non modifiés dans Git",
    TOOLTIP_INIT:                       "Initialiser le dépôt",
    TOOLTIP_CLONE:                      "Cloner le dépôt existant",
    TOOLTIP_COMMIT:                     "Commiter les fichiers sélectionnés",
    TOOLTIP_SHOW_UNTRACKED:             "Afficher non suivis",
    TOOLTIP_HIDE_UNTRACKED:             "Cacher non suivis",
    TOOLTIP_REFRESH_PANEL:              "Actualiser le panneau",
    TOOLTIP_HIDE_HISTORY:               "Cacher l'historique",
    TOOLTIP_SHOW_HISTORY:               "Afficher l'historique",
    TOOLTIP_PICK_REMOTE:                "Choisir le dépôt distant préféré",
    TOOLTIP_MORE:                       "Plus d'options\u2026",
    USER_ABORTED:                       "Annulation de l'utilisateur !",
    UNDO_CHANGES:                       "Annuler les changements",
    UNDO_LAST_LOCAL_COMMIT:             "Annuler le dernier commit local (non poussé)",
    URL:                                "URL",
    USE_CODE_INSPECTION:                "Utiliser l'inspection du Code",
    USE_GIT_GUTTER:                     "Utiliser le marquage Git gutter",
    USER_DATE_FORMAT:                   "Date format personnalisé (<a href='http://momentjs.com/docs/#/displaying/format/'>Syntaxe</a>)",
    USE_GITFTP:                         "Utiliser Git-FTP",
    USING_GIT_VERSION:                  "Version de Git",
    VIEW_AUTHORS_SELECTION:             "Voir les auteurs de la sélection",
    VIEW_AUTHORS_FILE:                  "Voir les auteurs du fichier"
});
