/*global define */

define({
    BUTTON_CANCEL:                      "Abbrechen",
    BUTTON_CHANGELOG:                   "Changelog zeigen",
    BUTTON_CLOSE:                       "Schließen",
    BUTTON_CLOSE_NOT_MODIFIED:          "Unveränderte Dateien schließen",
    BUTTON_COMMIT:                      "Commit",
    BUTTON_DEFAULTS:                    "Standard wiederherstellen",
    BUTTON_OK:                          "Okay",
    BUTTON_PULL:                        "Git Pull",
    BUTTON_PUSH:                        "Git Push",
    BUTTON_RESET:                       "Index leeren",
    BUTTON_SAVE:                        "Speichern",
    CHANGELOG:                          "Changelog",
    CHECK_GIT_SETTINGS:                 "Überprüfe die Git-Einstellungen",
    COMMIT_MESSAGE_PLACEHOLDER:         "Gib die Commit-Nachricht hier ein\u2026",
    DELETE_FILE:                        "Datei löschen",
    DIFF:                               "Diff",
    EXTENSION_WAS_UPDATED_TITLE:        "Die Erweiterung wurde auf Version {0} aktualisiert",
    FEATURE_SETTINGS:                   "Feature-Einstellungen",
    FILE_DELETED:                       "Gelöscht",
    FILE_MODIFIED:                      "Geändert",
    FILE_NEWFILE:                       "Neue Datei",
    FILE_STAGED:                        "Staged",
    FILE_UNTRACKED:                     "Untracked",
    FILE_RENAMED:                       "Umbenannt",
    FOR_WINDOWS_USERS:                  "Für Windows-Nutzer",
    GIT_COMMIT:                         "Git commit\u2026",
    GIT_DIFF:                           "Git diff &mdash;",
    GIT_IS_IN_PATH:                     "Git kann von überall aus abgerufen werden (ist im Systempfad, funktioniert evtl. nicht mit einem Mac)",
    GIT_PULL_RESPONSE:                  "Git Pull: Antwort",
    GIT_PUSH_RESPONSE:                  "Git Push: Antwort",
    GIT_SETTINGS:                       "Git-Einstellungen\u2026",
    LOADING:                            "Lädt\u2026",
    NOTHING_TO_COMMIT:                  "Nichts zum commiten, das Arbeitsverzeichnis ist sauber.",
    PATH_TO_GIT_EXECUTABLE:             "Pfad zur Git-Anwendung",
    PATH_TO_GIT_MSYSGIT:                "Pfad zum msysgit-Ordner",
    Q_DELETE_FILE:                      "Sind Sie sich sicher, dass Sie die Datei {0} löschen möchten?",
    Q_RESTART_BRACKETS:                 "Do you wish to restart Brackets to apply new settings ?",
    Q_UNDO_CHANGES:                     "Änderungen an der Datei {0} wirklich verwerfen?",
    RESTART:                            "Neu starten",
    STRIP_WHITESPACE_FROM_COMMITS:      "Anhängenden Whitespace von Commits entfernen",
    UNDO_CHANGES:                       "Änderungen verwerfen",
    USING_GIT_VERSION:                  "Git Version"
});
