/*jshint maxlen:false */

define({
    // ADVANCED_FEATURES_WARNING:          "This features are not recommended for basic Git users as they may cause you to lose code that has been already commited if used inproperly. Use with caution.",
    ADVANCED_FEATURES_WARNING:             "Diese Funktionen sind für normale Git-Nutzer nicht zu empfehlen, da sie unter Umständen bei falscher Benutzung bewirken, dass bereits committeter Code verloren geht. Passen Sie auf.",
    // ADD_ENDLINE_TO_THE_END_OF_FILE:     "Add endline at the end of file",
    ADD_ENDLINE_TO_THE_END_OF_FILE:        "Neue Zeile am Dateiende hinzufügen",
    // ADD_TO_GITIGNORE:                   "Add to .gitignore",
    ADD_TO_GITIGNORE:                      "Zu \".gitignore\" hinzufügen",
    // AGREE_TO_STORE_PASSWORDS:           "I agree that password are stored in plain text on my computer",
    AGREE_TO_STORE_PASSWORDS:              "Ich stimme zu, dass Passwörter im Klartext auf meinem Computer gespeichert werden",
    // AMEND_COMMIT:                       "Amend last commit",
    AMEND_COMMIT:                          "Letzten Commit abändern",
    // AMEND_COMMIT_FORBIDDEN:             "Cannot amend commit when there are no unpushed commits",
    AMEND_COMMIT_FORBIDDEN:                "Es kann kein Commit abgeändert werden, da es keine noch nicht versendeten Commits gibt",
    // AUTHOR:                             "Author",
    AUTHOR:                                "Autoren",
    // AUTHORS_OF:                         "Authors of",
    AUTHORS_OF:                            "Autoren von",
    // BASH_NOT_AVAILABLE:                 "Bash is not available or properly configured",
    BASH_NOT_AVAILABLE:                    "Bash ist nicht verfügbar oder richtig eingestellt",
    // BASIC_CONFIGURATION:                "Basic configuration",
    BASIC_CONFIGURATION:                   "Basis-Konfiguration",
    // BRACKETS_GIT_ERROR:                 "Brackets Git encountered an error\u2026",
    BRACKETS_GIT_ERROR:                    "Es ist ein Fehler in Brackets Git aufgetreten\u2026",
    // BRANCH_NAME:                        "Branch name",
    BRANCH_NAME:                           "Name des Branches",
    // BUTTON_CANCEL:                      "Cancel",
    BUTTON_CANCEL:                         "Abbrechen",
    // BUTTON_CHANGELOG:                   "Show changelog",
    BUTTON_CHANGELOG:                      "Changelog zeigen",
    // BUTTON_CLOSE:                       "Close",
    BUTTON_CLOSE:                          "Schließen",
    // BUTTON_DEFAULTS:                    "Restore defaults",
    BUTTON_DEFAULTS:                       "Standard wiederherstellen",
    // BUTTON_OK:                          "OK",
    BUTTON_OK:                             "Okay",
    // BUTTON_REPORT:                      "Report",
    BUTTON_REPORT:                         "Melden",
    // BUTTON_SAVE:                        "Save",
    BUTTON_SAVE:                           "Speichern",
    // BUTTON_COMMIT:                      "Commit",
    BUTTON_COMMIT:                         "Committen",
    // BUTTON_INIT:                        "Init",
    BUTTON_INIT:                           "Initialisieren",
    // BUTTON_CLONE:                       "Clone",
    BUTTON_CLONE:                          "Klonen",
    // BUTTON_CHECKOUT_COMMIT:             "Checkout",
    BUTTON_CHECKOUT_COMMIT:                "Auschecken",
    // BUTTON_RESET:                       "Reset index",
    BUTTON_RESET:                          "Setze Staging-Area um",
    // BUTTON_RESET_HARD:                  "Reset to this commit and discard the changes that came after it. (reset --hard)",
    BUTTON_RESET_HARD:                     "Auf diesen Commit umsetzen und alle nachfolgenden Änderungen verwerfen. (reset --hard)",
    // BUTTON_RESET_SOFT:                  "Reset to this commit and retain changes that came after it staged for a new commit. (reset --soft)",
    BUTTON_RESET_SOFT:                     "Auf diesen Commit umsetzen und nachfolgende Änderungen für einen Commit vorgemerkt behalten. (reset --soft)",
    // BUTTON_RESET_MIXED:                 "Reset to this commit and retain changes that came after it unstaged. (reset --mixed)",
    BUTTON_RESET_MIXED:                    "Auf diesen Commit umsetzen und nachfolgende Änderungen nicht zum Commit vorgemerkt behalten. (reset --mixed)",
    // CHANGELOG:                          "Changelog",
    CHANGELOG:                             "Changelog",
    // CHANGE_USER_NAME:                   "Change git username",
    CHANGE_USER_NAME:                      "Git-Nutzernamen ändern",
    // CHANGE_USER_EMAIL:                  "Change git email",
    CHANGE_USER_EMAIL:                     "Git-E-Mail-Adresse ändern",
    // CHECK_GIT_SETTINGS:                 "Check Git settings",
    CHECK_GIT_SETTINGS:                    "Überprüfe die Git-Einstellungen",
    // CODE_INSPECTION_PROBLEMS:           "Code inspection problems:",
    CODE_INSPECTION_PROBLEMS:              "Fehler beim Linten:",
    // COMMAND_ARGUMENTS:                  "Command arguments",
    COMMAND_ARGUMENTS:                     "Kommandozeilen-Argumente",
    // COMMIT:                             "Commit",
    COMMIT:                                "Commit",
    // COMMIT_ALL_SHORTCUT:                "Commit all files",
    COMMIT_ALL_SHORTCUT:                   "Alle Dateien committen",
    // COMMIT_CURRENT_SHORTCUT:            "Commit current file",
    COMMIT_CURRENT_SHORTCUT:               "Aktuelle Datei committen",
    // COMMIT_MESSAGE_PLACEHOLDER:         "Enter commit message here\u2026",
    COMMIT_MESSAGE_PLACEHOLDER:            "Gib die Commit-Beschreibung hier ein\u2026",
    // CLONE_REPOSITORY:                   "Clone repository",
    CLONE_REPOSITORY:                      "Repository klonen",
    // CREATE_NEW_BRANCH:                  "Create new branch\u2026",
    CREATE_NEW_BRANCH:                     "Neuen Branch erstellen\u2026",
    // CREATE_NEW_REMOTE:                  "Create new remote\u2026",
    CREATE_NEW_REMOTE:                     "Neues Remote-Repository hinzufügen\u2026",
    // CREATE_NEW_GITFTP_SCOPE:            "Create new Git-FTP remote\u2026",
    CREATE_NEW_GITFTP_SCOPE:               "Neues Git-FTP Remote-Repository hinzufügen\u2026",
    // CUSTOM_TERMINAL_COMMAND:            "Custom terminal command (sample: gnome-terminal or complete path to executable)",
    CUSTOM_TERMINAL_COMMAND:               "Eigener Konsolenbefehl (Beispiel: gnome-terminal oder der komplette Pfad zur Anwendung)",
    // CUSTOM_TERMINAL_COMMAND_HINT:       "Sample arguments: --window --working-directory=$1<br>$1 in arguments will be replaced by current project directory.",
    CUSTOM_TERMINAL_COMMAND_HINT:          "Beispielhafte Argumente: --window --working-directory=$1<br>$1 wird bei den Argumenten durch den Pfad des aktuellen Projekts ersetzt.",
    // DATE_FORMAT:                        "YYYY-MM-DD HH:mm:ss",
    DATE_FORMAT:                           "DD.MM.YYYY HH:mm:ss",
    // DATE_MODE_0:                        "Formatted using local date format",
    DATE_MODE_0:                           "Lokales Datumsformat",
    // DATE_MODE_1:                        "Relative time",
    DATE_MODE_1:                           "Relative Zeitangabe",
    // DATE_MODE_2:                        "Intelligent mode (relative/formatted)",
    DATE_MODE_2:                           "Intelligenter Modus (relativ/formatiert)",
    // DATE_MODE_3:                        "Formatted using your own format",
    DATE_MODE_3:                           "Eigenes Datumsformat",
    // DATE_MODE_4:                        "Original Git date",
    DATE_MODE_4:                           "Git-Datum",
    // DEBUG:                              "Debug",
    DEBUG:                                 "Debug",
    // DEBUG_MODE_SETTING:                 "DEBUG mode &mdash; Leave this OFF unless you need to find a problem with the extension. All Git communication will be forwarded to Brackets console!",
    DEBUG_MODE_SETTING:                    "DEBUG-Modus &mdash; Aktivieren Sie diesen Modus nur, wenn Sie ein Problem mit der Erweiterung eingrenzen müssen. Alle Git-Vorgänge werden in die Brackets-Konsole weitergeleitet!",
    // DELETE_FILE:                        "Delete file",
    DELETE_FILE:                           "Datei löschen",
    // DELETE_REMOTE:                      "Delete remote",
    DELETE_REMOTE:                         "Remote-Repository entfernen",
    // DELETE_REMOTE_NAME:                 "Do you really wish to delete remote \"{0}\"?",
    DELETE_REMOTE_NAME:                    "Wollen Sie das Remote-Repository \"{0}\" wirklich entfernen?",
    // DELETE_LOCAL_BRANCH:                "Delete local branch",
    DELETE_LOCAL_BRANCH:                   "Lokalen Branch entfernen",
    // DELETE_LOCAL_BRANCH_NAME:           "Do you really wish to delete local branch \"{0}\"?",
    DELETE_LOCAL_BRANCH_NAME:              "Wollen Sie den lokalen Branch \"{0}\" wirklich entfernen?",
    // TITLE_CHECKOUT:                     "Do you really wish to checkout this commmit?",
    TITLE_CHECKOUT:                        "Wollen Sie diesen Commit wirklich auschecken?",
    // DIALOG_CHECKOUT:                    "When checking out a commit, the repo will go into a DETACHED HEAD state. You can't make any commits unless you create a branch based on this.",
    DIALOG_CHECKOUT:                       "Nachdem ein Commit ausgecheckt wurde, hat das Repository einen losgelösten HEAD. Sie können nicht committen, bis Sie aus diesem Zustand heraus einen Branch erstellen.",
    // TITLE_RESET:                        "Do you really wish to reset?",
    TITLE_RESET:                           "Wollen Sie die Staging-Area wirklich umsetzen?",
    // DIALOG_RESET_HARD:                  "You will lose all changes after this commit!",
    DIALOG_RESET_HARD:                     "Sie werden alle Änderungen nach diesem Commit verlieren!",
    // DIALOG_RESET_MIXED:                 "Changes after this commit will be unstaged.",
    DIALOG_RESET_MIXED:                    "Änderungen nach diesem Commit werden nicht zum Commit vorgemerkt.",
    // DIALOG_RESET_SOFT:                  "Changes after this commit will be staged for a new commmit.",
    DIALOG_RESET_SOFT:                     "Änderungen nach diesem Commit werden für einen neuen Commit vorgemerkt.",
    // DIFF:                               "Diff",
    DIFF:                                  "Diff",
    // DIFF_FAILED_SEE_FILES:              "Git diff failed to provide diff results. This is the list of staged files to be commited:",
    DIFF_FAILED_SEE_FILES:                 "Git diff konnte keine Unterschiede finden. Hier ist die Liste der zum Commit vorgemerkten Dateien, die committet werden:",
    // ENTER_PASSWORD:                     "Enter password:",
    ENTER_PASSWORD:                        "Passwort eingeben:",
    // ENTER_USERNAME:                     "Enter username:",
    ENTER_USERNAME:                        "Nutzernamen eingeben:",
    // ENTER_REMOTE_GIT_URL:               "Enter Git URL of the repository you want to clone:",
    ENTER_REMOTE_GIT_URL:                  "Geben Sie die Git-URL des zu klonenden Repositories ein:",
    // ENTER_REMOTE_NAME:                  "Enter name of the new remote:",
    ENTER_REMOTE_NAME:                     "Geben Sie den Namen des neuen Remote-Repositories ein:",
    // ENTER_GITFTP_SCOPE_NAME:            "Enter name of the new Git-FTP remote:",
    ENTER_GITFTP_SCOPE_NAME:               "Geben Sie den Namen des neuen Git-FTP Remote-Repositories ein:",
    // ENTER_REMOTE_URL:                   "Enter URL of the new remote:",
    ENTER_REMOTE_URL:                      "Geben Sie die URL des neuen Remote-Repositories ein:",
    // ENTER_GITFTP_SCOPE_URL:             "Enter FTP URL of the new Git-FTP remote specifing username and password:",
    ENTER_GITFTP_SCOPE_URL:                "Geben Sie die FTP-URL des neuen Git-FTP Remote-Repositories unter Angabe von Nutzername und Passwort ein:",
    // ERROR_TERMINAL_NOT_FOUND:           "Terminal was not found for your OS, you can define a custom Terminal command in the settings",
    ERROR_TERMINAL_NOT_FOUND:              "Die Konsole wurde in ihrem Betriebssystem nicht gefunden, Sie können einen eigenen Konsolenbefehl in den Einstellungen angeben",
    // ERROR_CONNECT_NODEJS:               "Failed to connect to NodeJS. If you just updated the extension close all instances of Brackets and try starting again.",
    ERROR_CONNECT_NODEJS:                  "Es konnte keine Verbindung zu NodeJS aufgebaut werden. Schließen Sie alle Instanzen von Brackets und starten es erneut, wenn Sie die Erweiterung gerade aktualisiert haben.",
    // EXTENDED_COMMIT_MESSAGE:            "EXTENDED",
    EXTENDED_COMMIT_MESSAGE:               "ERWEITERT",
    // EXTENSION_WAS_UPDATED_TITLE:        "The extension was updated to {0}",
    EXTENSION_WAS_UPDATED_TITLE:           "Die Erweiterung wurde auf Version {0} aktualisiert",
    // ENTER_NEW_USER_NAME:                "Enter username",
    ENTER_NEW_USER_NAME:                   "Nutzernamen eingeben",
    // ENTER_NEW_USER_EMAIL:               "Enter email",
    ENTER_NEW_USER_EMAIL:                  "E-Mail-Adresse eingeben",
    // ENABLE_ADVANCED_FEATURES:           "Enable advanced features",
    ENABLE_ADVANCED_FEATURES:              "Erweiterte Funktionen aktivieren",
    // FEATURES:                           "Features",
    FEATURES:                              "Funktionen",
    // FILE_STAGED:                        "Staged",
    FILE_STAGED:                           "Zum Commit vorgemerkt",
    // FILE_UNMODIFIED:                    "Unmodified",
    // TODO: localize FILE_UNMODIFIED to de
    // FILE_IGNORED:                       "Ignored",
    // TODO: localize FILE_IGNORED to de
    // FILE_UNTRACKED:                     "Untracked",
    FILE_UNTRACKED:                        "Unbeobachtet",
    // FILE_MODIFIED:                      "Modified",
    FILE_MODIFIED:                         "Geändert",
    // FILE_ADDED:                         "New file",
    FILE_ADDED:                            "Neue Datei",
    // FILE_DELETED:                       "Deleted",
    FILE_DELETED:                          "Gelöscht",
    // FILE_RENAMED:                       "Renamed",
    FILE_RENAMED:                          "Umbenannt",
    // FILE_COPIED:                        "Copied",
    // TODO: localize FILE_COPIED to de
    // FILE_UNMERGED:                      "Unmerged",
    FILE_UNMERGED:                         "Nicht zusammengeführt",
    // FOR_MAC_LINUX_USERS:                "For Mac/Linux users",
    FOR_MAC_LINUX_USERS:                   "Für Mac-/Linux-Nutzer",
    // FOR_WINDOWS_USERS:                  "For Windows users",
    FOR_WINDOWS_USERS:                     "Für Windows-Nutzer",
    // GIT_COMMIT:                         "Git commit\u2026",
    GIT_COMMIT:                            "Git-Commit\u2026",
    // GIT_CONFIGURATION:                  "Git configuration",
    GIT_CONFIGURATION:                     "Git-Konfiguration",
    // GIT_DIFF:                           "Git diff &mdash;",
    GIT_DIFF:                              "Git-Unterschied &mdash;",
    // GIT_IS_IN_PATH:                     "Git can be called from anywhere (is in system path, might not work on Mac)",
    GIT_IS_IN_PATH:                        "Git kann von überall aus abgerufen werden (ist im Systempfad, funktioniert evtl. nicht mit einem Mac)",
    // GIT_PULL_RESPONSE:                  "Git Pull response",
    GIT_PULL_RESPONSE:                     "Git Pull: Antwort",
    // GIT_PUSH_RESPONSE:                  "Git Push response",
    GIT_PUSH_RESPONSE:                     "Git Push: Antwort",
    // GITFTP_PUSH_RESPONSE:               "Git-FTP Push response",
    GITFTP_PUSH_RESPONSE:                  "Git-FTP Push: Antwort",
    // GIT_SETTINGS:                       "Git Settings\u2026",
    GIT_SETTINGS:                          "Git-Einstellungen\u2026",
    // GIT_REMOTES:                        "Git remotes",
    GIT_REMOTES:                           "Git Remote-Repositories",
    // GITFTP_SCOPES:                      "Git-FTP remotes",
    GITFTP_SCOPES:                         "Git-FTP Remote-Repositories",
    // GOTO_PREVIOUS_GIT_CHANGE:           "Go to previous Git change",
    GOTO_PREVIOUS_GIT_CHANGE:              "Zur vorherigen Änderung springen",
    // GOTO_NEXT_GIT_CHANGE:               "Go to next Git change",
    GOTO_NEXT_GIT_CHANGE:                  "Zur nächsten Änderung springen",
    // HIDE_UNTRACKED:                     "Hide untracked",
    HIDE_UNTRACKED:                        "Unbeobachtete ausblenden",
    // INIT_GITFTP_SCOPE:                  "Initialize Git-FTP remote",
    INIT_GITFTP_SCOPE:                     "Git-FTP Remote-Repository initialisieren",
    // INIT_GITFTP_SCOPE_NAME:             "Initialize Git-FTP remote \"{0}\"?",
    INIT_GITFTP_SCOPE_NAME:                "Wollen Sie das Git-FTP Remote-Repository \"{0}\" wirklich initialisieren?",
    // LAUNCH_BASH_SHORTCUT:               "Bash/Terminal shortcut",
    LAUNCH_BASH_SHORTCUT:                  "Bash-Konsole öffnen",
    // LOADING:                            "Loading\u2026",
    LOADING:                               "Lädt\u2026",
    // LINES:                              "Lines",
    LINES:                                 "Zeilen",
    // _LINES:                             "lines",
    _LINES:                                "Zeilen",
    // LIST_MODIFIED_FILES:                "Modified files",
    LIST_MODIFIED_FILES:                   "Geänderte Dateien",
    // MARK_MODIFIED_FILES_IN_TREE:        "Mark modified files in file tree",
    MARK_MODIFIED_FILES_IN_TREE:           "Geänderte Dateien im Dateibaum markieren",
    // MERGE_BRANCH:                       "Merge branch",
    MERGE_BRANCH:                          "Branch zusammenführen",
    // MERGE_RESULT:                       "Merge result",
    MERGE_RESULT:                          "Merge-Ergebnis",
    // MERGE_MESSAGE:                      "Merge message",
    MERGE_MESSAGE:                         "Merge-Commit-Beschreibung",
    // NORMALIZE_LINE_ENDINGS:             "Normalize line endings (to \\n)",
    NORMALIZE_LINE_ENDINGS:                "Zeilenumbrüche normalisieren (zu \\n)",
    // NOTHING_TO_COMMIT:                  "Nothing to commit, working directory clean.",
    NOTHING_TO_COMMIT:                     "Nichts zum committen, das Arbeitsverzeichnis ist sauber.",
    // ORIGIN_BRANCH:                      "Origin branch",
    ORIGIN_BRANCH:                         "Ursprungs-Branch",
    // PANEL_COMMAND:                      "Show Git panel",
    PANEL_COMMAND:                         "Git-Panel anzeigen",
    // PANEL_SHORTCUT:                     "Toggle panel",
    PANEL_SHORTCUT:                        "Panel ein-/ausblenden",
    // PASSWORDS:                          "Passwords",
    PASSWORDS:                             "Passwörter",
    // PATH_TO_GIT_EXECUTABLE:             "Path to Git executable",
    PATH_TO_GIT_EXECUTABLE:                "Pfad zur Git-Anwendung",
    // PATH_TO_GIT_MSYSGIT:                "Path to msysgit folder",
    PATH_TO_GIT_MSYSGIT:                   "Pfad zum msysgit-Ordner",
    // PULL_SHORTCUT:                      "Pull from remote repository",
    PULL_SHORTCUT:                         "Vom Remote-Repository aktualisieren (\"Pull\")",
    // PUSH_SHORTCUT:                      "Push to remote repository",
    PUSH_SHORTCUT:                         "Zum Remote-Repository versenden (\"Push\")",
    // Q_DELETE_FILE:                      "Are you sure you wish to delete the file <span class='dialog-filename'>{0}</span>?",
    Q_DELETE_FILE:                         "Sind Sie sich sicher, dass Sie die Datei <span class='dialog-filename'>{0}</span> löschen möchten?",
    // Q_RESTART_BRACKETS:                 "Do you wish to restart Brackets to apply new settings?",
    Q_RESTART_BRACKETS:                    "Wollen Sie Brackets jetzt neu starten, um die geänderten Einstellungen zu übernehmen?",
    // Q_UNDO_CHANGES:                     "Reset changes to file <span class='dialog-filename'>{0}</span>?",
    Q_UNDO_CHANGES:                        "Änderungen an der Datei <span class='dialog-filename'>{0}</span> wirklich verwerfen?",
    // REMOVE_BOM:                         "Remove BOM from files",
    REMOVE_BOM:                            "BOM von Dateien entfernen",
    // REMOVE_FROM_GITIGNORE:              "Remove from .gitignore",
    REMOVE_FROM_GITIGNORE:                 "Aus \".gitignore\" entfernen",
    // RESTART:                            "Restart",
    RESTART:                               "Neu starten",
    // RESET_LOCAL_REPO:                   "Discard all changes since last commit",
    RESET_LOCAL_REPO:                      "Alle Änderungen seit dem letzten Commit verwerfen",
    // RESET_LOCAL_REPO_CONFIRM:           "Do you wish to discard all changes done since last commit? This action can't be reverted.",
    RESET_LOCAL_REPO_CONFIRM:              "Wollen Sie wirklich alle Änderungen seit dem letzten Commit verwerfen? Diese Aktion kann nicht rückgängig gemacht werden.",
    // SAVE_PASSWORD_QUESTION:             "Save username/password?",
    SAVE_PASSWORD_QUESTION:                "Wollen sie den Nutzernamen und das Passwort speichern?",
    // SET_ORIGIN_URL:                     "Set origin URL",
    SET_ORIGIN_URL:                        "Origin-URL einstellen",
    // SHORTCUTS:                          "Shortcuts",
    SHORTCUTS:                             "Tastenkürzel",
    // SHORTCUTS_HINT:                     "Separate keys with dash, like this: Ctrl-Alt-G<br>You can use the english key identifiers Ctrl, Cmd (Mac), Alt and Shift.",
    SHORTCUTS_HINT:                        "Trennen Sie Tasten mit Strichen, zum Beispiel: Ctrl-Alt-G<br>Sie können die englischen Bezeichnungen Ctrl (-> Strg), Cmd (Mac -> Command), Alt und Shift (-> Umschalt) nutzen.",
    // SHOW_BASH_TERMINAL_BUTTON:          "Show Bash/Terminal button in the panel",
    SHOW_BASH_TERMINAL_BUTTON:             "Den Bash-Button im Panel anzeigen",
    // SHOWN_DATE_FORMAT:                  "Format of commit dates in history",
    SHOWN_DATE_FORMAT:                     "Anzeigeformat des Datums eines Commits im Verlauf",
    // SHOW_REPORT_BUG_BUTTON:             "Show Report Bug button in the panel",
    SHOW_REPORT_BUG_BUTTON:                "Den \"Bug melden\"-Button im Panel anzeigen",
    // SHOW_UNTRACKED:                     "Show untracked",
    SHOW_UNTRACKED:                        "Unbeobachtete anzeigen",
    // STRIP_WHITESPACE_FROM_COMMITS:      "Strip trailing whitespace from commits",
    STRIP_WHITESPACE_FROM_COMMITS:         "Anhängende Leerzeichen von Commits entfernen",
    // TARGET_BRANCH:                      "Target branch",
    TARGET_BRANCH:                         "Ziel",
    // TOOLTIP_BUG:                        "Report bug",
    TOOLTIP_BUG:                           "Bug melden",
    // TOOLTIP_OPEN_BASH:                  "Open Bash/Terminal console",
    TOOLTIP_OPEN_BASH:                     "Bash-Konsole öffnen",
    // TOOLTIP_PULL:                       "Git Pull",
    TOOLTIP_PULL:                          "Vom Remote-Repository aktualisieren (\"Pull\")",
    // TOOLTIP_PUSH:                       "Git Push",
    TOOLTIP_PUSH:                          "Zum Remote-Repository versenden (\"Push\")",
    // TOOLTIP_GITPUSH:                    "Git-FTP Push",
    TOOLTIP_GITPUSH:                       "Zum Git-FTP Remote-Repository versenden (\"Push\")",
    // TOOLTIP_CLOSE_NOT_MODIFIED:         "Close files not modified in Git",
    TOOLTIP_CLOSE_NOT_MODIFIED:            "In Git unveränderte Dateien schließen",
    // TOOLTIP_INIT:                       "Initialize repository",
    TOOLTIP_INIT:                          "Repository initialisieren",
    // TOOLTIP_CHECKOUT_COMMIT:            "Checkout a specific commit",
    TOOLTIP_CHECKOUT_COMMIT:               "Einen bestimmten Commit auschecken",
    // TOOLTIP_CLONE:                      "Clone existing repository",
    TOOLTIP_CLONE:                         "Bereits existierendes Repository klonen",
    // TOOLTIP_COMMIT:                     "Commit the selected files",
    TOOLTIP_COMMIT:                        "Ausgewählte Dateien committen",
    // TOOLTIP_REFRESH_PANEL:              "Refresh panel",
    TOOLTIP_REFRESH_PANEL:                 "Panel aktualisieren",
    // TOOLTIP_HIDE_HISTORY:               "Hide history",
    TOOLTIP_HIDE_HISTORY:                  "Verlauf ausblenden",
    // TOOLTIP_SHOW_HISTORY:               "Show history",
    TOOLTIP_SHOW_HISTORY:                  "Verlauf anzeigen",
    // TOOLTIP_HIDE_FILE_HISTORY:          "Hide file history",
    TOOLTIP_HIDE_FILE_HISTORY:             "Dateiverlauf ausblenden",
    // TOOLTIP_SHOW_FILE_HISTORY:          "Show file history",
    TOOLTIP_SHOW_FILE_HISTORY:             "Dateiverlauf anzeigen",
    // TOOLTIP_PICK_REMOTE:                "Pick preferred remote",
    TOOLTIP_PICK_REMOTE:                   "Bevorzugtes Remote-Repository wählen",
    // TOOLTIP_MORE:                       "More actions\u2026",
    TOOLTIP_MORE:                          "Mehr Aktionen\u2026",
    // USER_ABORTED:                       "User aborted!",
    USER_ABORTED:                          "Nutzer abgelehnt!",
    // UNDO_CHANGES:                       "Discard changes",
    UNDO_CHANGES:                          "Änderungen verwerfen",
    // UNDO_LAST_LOCAL_COMMIT:             "Undo last local (not pushed) commit",
    UNDO_LAST_LOCAL_COMMIT:                "Letzten lokalen (nicht versendeten) Commit rückgängig machen",
    // URL:                                "URL",
    URL:                                   "URL",
    // USE_CODE_INSPECTION:                "Use Code inspection",
    USE_CODE_INSPECTION:                   "Linter nutzen",
    // USE_GIT_GUTTER:                     "Use Git gutter marks",
    USE_GIT_GUTTER:                        "Git-Markierungen am Rand anzeigen",
    // USER_DATE_FORMAT:                   "Own date format (<a href='http://momentjs.com/docs/#/displaying/format/'>Syntax</a>)",
    USER_DATE_FORMAT:                      "Eigenes Datumsformat (<a href='http://momentjs.com/docs/#/displaying/format/'>Syntax</a>)",
    // USE_GITFTP:                         "Use Git-FTP",
    USE_GITFTP:                            "Git-FTP benutzen",
    // USING_GIT_VERSION:                  "Git version",
    USING_GIT_VERSION:                     "Git-Version",
    // VIEW_AUTHORS_SELECTION:             "View authors of selection",
    VIEW_AUTHORS_SELECTION:                "Autoren der Auswahl anzeigen",
    // VIEW_AUTHORS_FILE:                  "View authors of file"
    VIEW_AUTHORS_FILE:                     "Autoren der Datei anzeigen"
});
