/*jshint maxlen:false */

define({
    ADD_ENDLINE_TO_THE_END_OF_FILE:     "Neue Zeile am Dateiende hinzufügen",
    ADD_TO_GITIGNORE:                   "Zu \".gitignore\" hinzufügen",
    AGREE_TO_STORE_PASSWORDS:           "Ich stimme zu, dass Passwörter im Klartext auf meinem Computer gespeichert werden",
    AMEND_COMMIT:                       "Letzten Commit abändern",
    AMEND_COMMIT_FORBIDDEN:             "Es kann kein Commit abgeändert werden, da es keine noch nicht versendeten Commits gibt",
    AUTHOR:                             "Autoren",
    AUTHORS_OF:                         "Autoren von",
    BASH_NOT_AVAILABLE:                 "Bash ist nicht verfügbar oder richtig eingestellt",
    BASIC_CONFIGURATION:                "Basis-Konfiguration",
    BRACKETS_GIT_ERROR:                 "Es ist ein Fehler in Brackets Git aufgetreten\u2026",
    BRANCH_NAME:                        "Name des Branches",
    BUTTON_CANCEL:                      "Abbrechen",
    BUTTON_CHANGELOG:                   "Changelog zeigen",
    BUTTON_CLOSE:                       "Schließen",
    BUTTON_DEFAULTS:                    "Standard wiederherstellen",
    BUTTON_OK:                          "Okay",
    BUTTON_REPORT:                      "Melden",
    BUTTON_SAVE:                        "Speichern",
    BUTTON_COMMIT:                      "Committen",
    BUTTON_INIT:                        "Initialisieren",
    BUTTON_CLONE:                       "Klonen",
    CHANGELOG:                          "Changelog",
    CHANGE_USER_NAME:                   "Git-Nutzernamen ändern",
    CHANGE_USER_EMAIL:                  "Git-E-Mail-Adresse ändern",
    CHECK_GIT_SETTINGS:                 "Überprüfe die Git-Einstellungen",
    CODE_INSPECTION_PROBLEMS:           "Fehler beim Linten:",
    COMMAND_ARGUMENTS:                  "Kommandozeilen-Argumente",
    COMMIT:                             "Commit",
    COMMIT_ALL_SHORTCUT:                "Alle Dateien committen",
    COMMIT_CURRENT_SHORTCUT:            "Aktuelle Datei committen",
    COMMIT_MESSAGE_PLACEHOLDER:         "Gib die Commit-Beschreibung hier ein\u2026",
    CLONE_REPOSITORY:                   "Repository klonen",
    CREATE_NEW_BRANCH:                  "Neuen Branch erstellen\u2026",
    CREATE_NEW_REMOTE:                  "Neues Remote-Repository hinzufügen\u2026",
    CREATE_NEW_GITFTP_REMOTE:           "Neues Git-FTP Remote-Repository hinzufügen\u2026",
    CUSTOM_TERMINAL_COMMAND:            "Eigener Konsolenbefehl (Beispiel: gnome-terminal oder der komplette Pfad zur Anwendung)",
    CUSTOM_TERMINAL_COMMAND_HINT:       "Beispielhafte Argumente: --window --working-directory=$1<br>$1 wird bei den Argumenten durch den Pfad des aktuellen Projekts ersetzt.",
    DATE_FORMAT:                        "DD.MM.YYYY HH:mm:ss",
    DATE_MODE_0:                        "Lokales Datumsformat",
    DATE_MODE_1:                        "Relative Zeitangabe",
    DATE_MODE_2:                        "Intelligenter Modus (relativ/formatiert)",
    DATE_MODE_3:                        "Eigenes Datumsformat",
    DATE_MODE_4:                        "Git-Datum",
    DEBUG:                              "Debug",
    DEBUG_MODE_SETTING:                 "DEBUG-Modus &mdash; Aktivieren Sie diesen Modus nur, wenn Sie ein Problem mit der Erweiterung eingrenzen müssen. Alle Git-Vorgänge werden in die Brackets-Konsole weitergeleitet!",
    DELETE_FILE:                        "Datei löschen",
    DELETE_REMOTE:                      "Remote-Repository entfernen",
    DELETE_REMOTE_NAME:                 "Wollen Sie das Remote-Repository \"{0}\" wirklich entfernen?",
    DIFF:                               "Diff",
    DIFF_FAILED_SEE_FILES:              "Git diff konnte keine Unterschiede finden. Hier ist die Liste der zum Commit vorgemerkten Dateien, die committet werden:",
    ENTER_PASSWORD:                     "Passwort eingeben:",
    ENTER_USERNAME:                     "Nutzernamen eingeben:",
    ENTER_REMOTE_GIT_URL:               "Geben Sie die Git-URL des zu klonenden Repositories ein:",
    ENTER_REMOTE_NAME:                  "Geben Sie den Namen des neuen Remote-Repositories ein:",
    ENTER_GITFTP_REMOTE_NAME:           "Geben Sie den Namen des neuen Git-FTP Remote-Repositories ein:",
    ENTER_REMOTE_URL:                   "Geben Sie die URL des neuen Remote-Repositories ein:",
    ENTER_GITFTP_REMOTE_URL:            "Geben Sie die FTP-URL des neuen Git-FTP Remote-Repositories unter Angabe von Nutzername und Passwort ein:",
    ERROR_TERMINAL_NOT_FOUND:           "Die Konsole wurde in ihrem Betriebssystem nicht gefunden, Sie können einen eigenen Konsolenbefehl in den Einstellungen angeben",
    EXTENDED_COMMIT_MESSAGE:            "ERWEITERT",
    EXTENSION_WAS_UPDATED_TITLE:        "Die Erweiterung wurde auf Version {0} aktualisiert",
    ENTER_NEW_USER_NAME:                "Nutzernamen eingeben",
    ENTER_NEW_USER_EMAIL:               "E-Mail-Adresse eingeben",
    FEATURES:                           "Funktionen",
    FILE_DELETED:                       "Gelöscht",
    FILE_MODIFIED:                      "Geändert",
    FILE_NEWFILE:                       "Neue Datei",
    FILE_RENAMED:                       "Umbenannt",
    FILE_STAGED:                        "Zum Commit vorgemerkt",
    FILE_UNTRACKED:                     "Unbeobachtet",
    FILE_UNMERGED:                      "Nicht zusammengeführt",
    FOR_MAC_LINUX_USERS:                "Für Mac-/Linux-Nutzer",
    FOR_WINDOWS_USERS:                  "Für Windows-Nutzer",
    GIT_COMMIT:                         "Git-Commit\u2026",
    GIT_CONFIGURATION:                  "Git-Konfiguration",
    GIT_DIFF:                           "Git-Unterschied &mdash;",
    GIT_IS_IN_PATH:                     "Git kann von überall aus abgerufen werden (ist im Systempfad, funktioniert evtl. nicht mit einem Mac)",
    GIT_PULL_RESPONSE:                  "Git Pull: Antwort",
    GIT_PUSH_RESPONSE:                  "Git Push: Antwort",
    GITFTP_PUSH_RESPONSE:               "Git-FTP Push: Antwort",
    GIT_SETTINGS:                       "Git-Einstellungen\u2026",
    GIT_REMOTES:                        "Git Remote-Repositories",
    GITFTP_REMOTES:                     "Git-FTP Remote-Repositories",
    GOTO_PREVIOUS_GIT_CHANGE:           "Zur vorherigen Änderung springen",
    GOTO_NEXT_GIT_CHANGE:               "Zur nächsten Änderung springen",
    INIT_GITFTP_REMOTE_NAME:            "Wollen Sie das Git-FTP Remote-Repository \"{0}\" wirklich initialisieren?",
    LAUNCH_BASH_SHORTCUT:               "Bash-Konsole öffnen",
    LOADING:                            "Lädt\u2026",
    LINES:                              "Zeilen",
    _LINES:                             "Zeilen",
    LIST_MODIFIED_FILES:                "Geänderte Dateien",
    MARK_MODIFIED_FILES_IN_TREE:        "Geänderte Dateien im Dateibaum markieren",
    MERGE_BRANCH:                       "Branch zusammenführen",
    MERGE_RESULT:                       "Ergebnis des Merges",
    NOTHING_TO_COMMIT:                  "Nichts zum committen, das Arbeitsverzeichnis ist sauber.",
    PANEL_COMMAND:                      "Git-Panel anzeigen",
    PANEL_SHORTCUT:                     "Panel ein-/ausblenden",
    PASSWORDS:                          "Passwörter",
    PATH_TO_GIT_EXECUTABLE:             "Pfad zur Git-Anwendung",
    PATH_TO_GIT_MSYSGIT:                "Pfad zum msysgit-Ordner",
    PULL_SHORTCUT:                      "Vom Remote-Repository aktualisieren (\"Pull\")",
    PUSH_SHORTCUT:                      "Zum Remote-Repository versenden (\"Push\")",
    Q_DELETE_FILE:                      "Sind Sie sich sicher, dass Sie die Datei <span class='dialog-filename'>{0}</span> löschen möchten?",
    Q_RESTART_BRACKETS:                 "Wollen Sie Brackets jetzt neu starten, um die geänderten Einstellungen zu übernehmen?",
    Q_UNDO_CHANGES:                     "Änderungen an der Datei <span class='dialog-filename'>{0}</span> wirklich verwerfen?",
    REMOVE_FROM_GITIGNORE:              "Aus \".gitignore\" entfernen",
    RESTART:                            "Neu starten",
    SAVE_PASSWORD_QUESTION:             "Wollen sie den Nutzernamen und das Passwort speichern?",
    SET_ORIGIN_URL:                     "Origin-URL einstellen",
    SHORTCUTS:                          "Tastenkürzel",
    SHORTCUTS_HINT:                     "Trennen Sie Tasten mit Strichen, zum Beispiel: Ctrl-Alt-G<br>Sie können die englischen Bezeichnungen Ctrl (-> Strg), Cmd (Mac -> Command), Alt und Shift (-> Umschalt) nutzen.",
    SHOW_BASH_TERMINAL_BUTTON:          "Den Bash-Button im Panel anzeigen",
    SHOWN_DATE_FORMAT:                  "Anzeigeformat des Datums eines Commits im Verlauf",
    SHOW_REPORT_BUG_BUTTON:             "Den \"Bug melden\"-Button im Panel anzeigen",
    STRIP_WHITESPACE_FROM_COMMITS:      "Anhängende Leerzeichen von Commits entfernen",
    TARGET_BRANCH:                      "Ziel",
    TOOLTIP_BUG:                        "Bug melden",
    TOOLTIP_OPEN_BASH:                  "Bash-Konsole öffnen",
    TOOLTIP_PULL:                       "Vom Remote-Repository aktualisieren (\"Pull\")",
    TOOLTIP_PUSH:                       "Zum Remote-Repository versenden (\"Push\")",
    TOOLTIP_GITPUSH:                    "Zum Git-FTP Remote-Repository versenden (\"Push\")",
    TOOLTIP_CLOSE_NOT_MODIFIED:         "In Git unveränderte Dateien schließen",
    TOOLTIP_INIT:                       "Repository initialisieren",
    TOOLTIP_CLONE:                      "Bereits existierendes Repository klonen",
    TOOLTIP_COMMIT:                     "Ausgewählte Dateien committen",
    TOOLTIP_SHOW_UNTRACKED:             "Unbeobachtete anzeigen",
    TOOLTIP_HIDE_UNTRACKED:             "Unbeobachtete ausblenden",
    TOOLTIP_REFRESH_PANEL:              "Panel aktualisieren",
    TOOLTIP_HIDE_HISTORY:               "Verlauf ausblenden",
    TOOLTIP_SHOW_HISTORY:               "Verlauf anzeigen",
    TOOLTIP_PICK_REMOTE:                "Bevorzugtes Remote-Repository wählen",
    TOOLTIP_MORE:                       "Mehr Aktionen\u2026",
    UNDO_CHANGES:                       "Änderungen verwerfen",
    UNDO_LAST_LOCAL_COMMIT:             "Letzten lokalen (nicht versendeten) Commit rückgängig machen",
    URL:                                "URL",
    USE_CODE_INSPECTION:                "Linter nutzen",
    USE_GIT_GUTTER:                     "Git-Markierungen am Rand anzeigen",
    USER_DATE_FORMAT:                   "Eigenes Datumsformat (<a href='http://momentjs.com/docs/#/displaying/format/'>Synthax</a>)",
    USE_GITFTP:                         "Git-FTP benutzen",
    USING_GIT_VERSION:                  "Git-Version",
    VIEW_AUTHORS_SELECTION:             "Autoren der Auswahl anzeigen",
    VIEW_AUTHORS_FILE:                  "Autoren der Datei anzeigen"
});

/* Last translated for 956973b3756e5de1a149cdad7fe712aca9e4f1eb */
