define({
    ACTION:                             "Åtgärd",
    ADD_ENDLINE_TO_THE_END_OF_FILE:     "Lägg till sluttecknen vid slutet av filen",
    ADD_TO_GITIGNORE:                   "Lägg till på .gitignore",
    ADVANCED_FEATURES_WARNING:          "Dessa funktioner är inte rekomenderade för standard Git användaren eftersom det finns en risk att du förlorar källkod som redan har commitats om funktionerna används felaktigt. Var försiktig.",
    AMEND_COMMIT:                       "Ändra senaste comiten",
    AMEND_COMMIT_FORBIDDEN:             "Kan inte ändra commiten eftersom det inte finns några opushade commits",
    _ANOTHER_BRANCH:                    "annan gren",
    AUTHOR:                             "Författare",
    AUTHORS_OF:                         "Författare av",
    AVATAR_TYPE:                        "Avatartyp",
    BASH_NOT_AVAILABLE:                 "Bash är inte tillgängligt eller felaktigt inställd",
    BASIC_CONFIGURATION:                "Grundläggande konfigurering",
    BLACK_WHITE_AVATAR:                 "Svartvid avatar",
    BRACKETS_GIT_ERROR:                 "Brackets Git påträffat ett fel\u2026",
    BRANCH_NAME:                        "Gren-namn",
    BUTTON_CANCEL:                      "Avbryt",
    BUTTON_CHANGELOG:                   "Visa ändringsloggen",
    BUTTON_CHECKOUT_COMMIT:             "Checka-ut",
    BUTTON_CLONE:                       "Klona",
    BUTTON_CLOSE:                       "Stäng",
    BUTTON_COMMIT:                      "Commit",
    BUTTON_DEFAULTS:                    "Återställ",
    BUTTON_FIND_CONFLICTS:              "Hitta konflikter\u2026",
    BUTTON_INIT:                        "Initsiera",
    BUTTON_MERGE_ABORT:                 "Avbryt sammanfogning",
    BUTTON_OK:                          "OK",
    BUTTON_REBASE_ABORT:                "Avstyr",
    BUTTON_REBASE_CONTINUE:             "Fortsätt med rebase",
    BUTTON_REBASE_SKIP:                 "Skippa",
    BUTTON_REPORT:                      "Rapport",
    BUTTON_RESET:                       "Återställ index",
    BUTTON_RESET_HARD:                  "Återställ denna commit och kasta alla ändringarna efter det. (reset --hard)",
    BUTTON_RESET_MIXED:                 "Återställ denna commit men behåll ändringarna efter som unstaged. (reset --mixed)",
    BUTTON_RESET_SOFT:                  "Återställ denna commit and behåll ändringarna efter som staged till en ny commit. (reset --soft)",
    BUTTON_SAVE:                        "Spara",
    CANCEL:                             "Avbryt",
    CHANGELOG:                          "Ändŕingslogg",
    CHANGE_USER_EMAIL:                  "Ändra Git-eposten",
    CHANGE_USER_NAME:                   "Ändra Git-användarnamnet",
    CHECK_GIT_SETTINGS:                 "Kunde inte starta git-binären - kontrollera git inställningarna och starta om Brackets",
    CLEAN_FILE_END:                     "Filer städade",
    CLEAN_FILE_START:                   "Städar filer",
    CLEANING_WHITESPACE_PROGRESS:       "Städa filer från blank-steg\u2026",
    CLEAR_WHITESPACE_ON_FILE_SAVE:      "Städa filer från blank-steg när filen sparas",
    CLONE_REPOSITORY:                   "Klona arkivet",
    CODE_INSPECTION_PROBLEMS:           "Fel vid källkodsinspektion:",
    COLLAPSE_ALL:                       "Fäll ihop alla",
    COLORED_AVATAR:                     "Avatarer i färg",
    COMMAND_ARGUMENTS:                  "Kommandotargument",
    COMMIT:                             "Commita",
    COMMIT_ALL_SHORTCUT:                "Commita alla filer",
    COMMIT_CURRENT_SHORTCUT:            "Commita nuvarande fil",
    COMMIT_MESSAGE_PLACEHOLDER:         "Skriv ett commit-meddelande här\u2026",
    CREATE_NEW_BRANCH:                  "Skapa en ny gren\u2026",
    CREATE_NEW_GITFTP_SCOPE:            "Skapa en ny Git-FTP remote\u2026",
    CREATE_NEW_REMOTE:                  "Skapa en ny remote\u2026",
    CURRENT_TRACKING_BRANCH:            "Följer nuvarande gren",
    _CURRENT_TRACKING_BRANCH:           "följer nuvarande gren",
    CUSTOM_TERMINAL_COMMAND:            "Anpassat terminalkommando (exempel: gnome-terminal eller komplett sökväg till binär)",
    CUSTOM_TERMINAL_COMMAND_HINT:       "Exempel på argument: --window --working-directory=$1<br>$1 argumenten kommer att ersättas av den aktuella projektkatalogen.",
    DATE_FORMAT:                        "MM/DD/YYYY HH:mm:ss",
    DATE_MODE_0:                        "Formaterad med lokalt datumformat",
    DATE_MODE_1:                        "Relativ tid",
    DATE_MODE_2:                        "Intelligent läge (relativt / formaterat)",
    DATE_MODE_3:                        "Formaterad med ditt eget format",
    DATE_MODE_4:                        "Original Git-datum",
    DEBUG:                              "FELSÖK",
    DEBUG_MODE_SETTING:                 "Felsökningsläge &mdash; Lämna detta AV om du inte upplevcer ett problem med tillägget. All Git-kommunikation kommer att vidarebefordras till Brackets-konsolen!",
    DEFAULT_GIT_TIMEOUT:                "Standard-timeouten för Git-operation (i sekunder)",
    DELETE_FILE:                        "Ta bort fil",
    DELETE_LOCAL_BRANCH:                "Ta bort lokal gren",
    DELETE_LOCAL_BRANCH_NAME:           "Vill du verkligen ta bort den lokala grenen \"{0}\"?",
    DELETE_REMOTE:                      "Ta bort remote",
    DELETE_REMOTE_NAME:                 "Vill du verkligen ta bort en remote \"{0}\"?",
    DELETE_SCOPE:                       "Radera Git-FTP-omfattning",
    DELETE_SCOPE_NAME:                  "Vill du verkligen ta bort Git-FTP-omfattning \"{0}\"?",
    DIALOG_CHECKOUT:                    "När du checkar ut en commit kommer ditt repo att gå till ett DETACHED HEAD-tillstånd. Du kan inte göra några commits om du inte skapar en gren baserad på denna.",
    DIALOG_PULL_TITLE:                  "Hämta från en remote",
    DIALOG_PUSH_TITLE:                  "Skicka till en remote",
    DIALOG_RESET_HARD:                  "Du kommer förlorara alla ändringar efter denna commit!",
    DIALOG_RESET_MIXED:                 "Förändringar efter dena commit kommer bli unstaged.",
    DIALOG_RESET_SOFT:                  "Förändringar efter dena commit kommer bli staged för en ny commit.",
    DIFF:                               "Differens",
    DIFFTOOL:                           "Differens med difftool",
    DIFF_FAILED_SEE_FILES:              "Git kunde inte skapa en differens på filerna. Detta är en lista över markerade filer som kommer att commitas:",
    DIFF_TOO_LONG:                      "Differensen är för lång för att kunna visas",
    ENABLE_ADVANCED_FEATURES:           "Aktivera avancerade funktioner",
    ENABLE_GERRIT_PUSH_REF:             "Använd Gerrit-kompatibel push ref",
    ENTER_GITFTP_SCOPE_NAME:            "Ange namnet för den nya Git-FTP remote:",
    ENTER_GITFTP_SCOPE_URL:             "Ange FTP-URL för den nya Git-FTP remote ange både användarnamn och lösenord:",
    ENTER_NEW_USER_EMAIL:               "Ange e-postadress",
    ENTER_NEW_USER_NAME:                "Ange användarnamn",
    ENTER_PASSWORD:                     "Ange lösenord:",
    ENTER_REMOTE_GIT_URL:               "Ange en Git URL till det arkiv som du vill klona:",
    ENTER_REMOTE_NAME:                  "Ange ett namn för denna nya remote:",
    ENTER_REMOTE_URL:                   "Ange en URL för denna nya remote:",
    ENTER_USERNAME:                     "Ange användarnamn:",
    ERROR_CONNECT_NODEJS:               "Kunde inte ansluta till NodeJS. Om du nyligen har uppdaterat tillägget stänger du alla instanser av Brackets och försök starta igen. Om en omstart inte hjälper, försök då att ta bort andra tillägg som du har installerat eftersom något av dom förmodligen orsakar problem.",
    ERROR_NOTHING_SELECTED:             "Ingenting är markerat!",
    ERROR_SAVE_FIRST:                   "Spara dokumentet först!",
    ERROR_TERMINAL_NOT_FOUND:           "Terminalen hittades inte för ditt operativsystem, du kan definiera ett anpassat terminalkommando i inställningarna",
    EXPAND_ALL:                         "Expandera alla",
    EXTENDED_COMMIT_MESSAGE:            "UTÖKAD",
    EXTENSION_WAS_UPDATED_TITLE:        "Tillägget har uppdaterades till {0}",
    FEATURES:                           "Funktioner",
    FILE_ADDED:                         "Ny fil",
    FILE_COPIED:                        "Kopierad",
    FILE_DELETED:                       "Borttagen",
    FILE_IGNORED:                       "Ignored",
    FILE_MODIFIED:                      "Ändrad",
    FILE_RENAMED:                       "Omdöpt",
    FILE_STAGED:                        "Staged",
    FILE_UNMERGED:                      "Ej sammanfogad",
    FILE_UNMODIFIED:                    "Oförändrad",
    FILE_UNTRACKED:                     "Spåras inte",
    FOR_MAC_LINUX_USERS:                "För Mac/Linux-användare",
    FOR_WINDOWS_USERS:                  "För Windows-användare",
    GETTING_STAGED_DIFF_PROGRESS:       "Hämtar differensen av filer som är stagede\u2026",
    GITFTP_PUSH_RESPONSE:               "Git-FTP Push svar",
    GITFTP_SCOPES:                      "Git-FTP fjärr",
    GIT_COMMIT:                         "Git commit\u2026",
    GIT_CONFIGURATION:                  "Git konfiguration",
    GIT_DIFF:                           "Git differens &mdash;",
    GIT_PULL_RESPONSE:                  "Git Pull svar",
    GIT_PUSH_RESPONSE:                  "Git Push svar",
    GIT_REMOTES:                        "Git fjärr",
    GIT_SETTINGS:                       "Git inställningar\u2026",
    GOTO_NEXT_GIT_CHANGE:               "å till nästa Git-förändring",
    GOTO_PREVIOUS_GIT_CHANGE:           "Gå till tidigare Git-ändring",
    GUTTER_CLICK_DETAILS:               "Klicka för mer information",
    HIDE_UNTRACKED:                     "Dölj ospårade",
    HISTORY:                            "Historik",
    HISTORY_COMMIT_BY:                  "av",
    IDENTICON:                          "Identicon (www.gravatar.com)",
    INIT_GITFTP_SCOPE:                  "Initiera Git-FTP fjärr",
    INIT_GITFTP_SCOPE_NAME:             "Initiera Git-FTP fjärr \"{0}\"?",
    LAUNCH_BASH_SHORTCUT:               "Bash/Terminalgenväg",
    LINES:                              "Rader",
    _LINES:                             "rader",
    LIST_MODIFIED_FILES:                "Ändrade filer",
    LOADING:                            "Läser in\u2026",
    MARK_MODIFIED_FILES_IN_TREE:        "Markera ändrade filer i filträdet",
    MERGE_BRANCH:                       "Merge gren",
    MERGE_MESSAGE:                      "Merge meddelande",
    MERGE_RESULT:                       "Merge resultat",
    MORE_INFO:                          "Mer information\u2026",
    NORMALIZE_LINE_ENDINGS:             "Normalisera linjeavslut (till \\n)",
    NOTHING_TO_COMMIT:                  "Inget att commita, arbetskatalogen är ren.",
    OK:                                 "OK",
    OPERATION_IN_PROGRESS_TITLE:        "Git-operation pågår\u2026",
    ORIGIN_BRANCH:                      "Ursprungs-gren",
    PANEL_COMMAND:                      "Visa Git panel",
    PANEL_SHORTCUT:                     "Växla panel",
    PASSWORD:                           "Lösenordet",
    PASSWORDS:                          "Lösenord",
    PATH_TO_GIT_EXECUTABLE:             "Sökväg till Git-binär",
    PATH_TO_GIT_MSYSGIT:                "Sökväg till msysgit-mapp",
    PICTURE:                            "Gravatar (www.gravatar.com)",
    PULL_AVOID_MERGING:                 "Undvik manuell sammanslagning",
    PULL_DEFAULT:                       "Standard-sammanfogning",
    PULL_FROM:                          "Hämta från",
    PULL_MERGE_NOCOMMIT:                "Sammanfoga utan commit",
    PULL_REBASE:                        "Använd rebase",
    PULL_RESET:                         "Använd mjuk återställning",
    PULL_SHORTCUT:                      "Hämta från fjärr-arkiv",
    PUSH_DEFAULT:                       "Standard hämtning",
    PUSH_DELETE_BRANCH:                 "Ta bort fjärr-arkiv",
    PUSH_SEND_TAGS:                     "Skicka taggar",
    PUSH_FORCED:                        "Tvingad hämtning",
    PUSH_SHORTCUT:                      "Skicka till fjärr-arkiv",
    PUSH_TO:                            "Skicka till",
    Q_DELETE_FILE:                      "Är du säker på att du vill ta bort filen <span class='dialog-filename'>{0}</span>?",
    Q_RESTART_BRACKETS:                 "Vill du starta om Brackets för att tillämpa de nya inställningarna?",
    Q_UNDO_CHANGES:                     "Återställ ändringar på filen <span class='dialog-filename'>{0}</span>?",
    REBASE_RESULT:                      "Rebase resultat",
    REFRESH_GIT:                        "Förnya Git",
    REMOVE_BOM:                         "Ta bort BOM från filer",
    REMOVE_FROM_GITIGNORE:              "Ta bort från .gitignore",
    REQ_INTERNET:                       "Kräver internetuppkoppling",
    RESET_LOCAL_REPO:                   "Kasta alla ändringar sedan senaste commiten",
    RESET_LOCAL_REPO_CONFIRM:           "Vill du kasta alla ändringar som gjorts sedan den senaste commiten? Denna åtgärden kan inte återställas.",
    RESTART:                            "Omstart",
    SAVE_CREDENTIALS_HELP:              "Du behöver inte fylla i användarnamn / lösenord om dina uppgifter hanteras någon annanstans. Använd endast detta när din åtgärder fortsätter att gå fel.",
    SAVE_CREDENTIALS_IN_URL:            "Spara dina uppgifter till fjärr-url (i klartext)",
    SAVE_PASSWORD_QUESTION:             "Spara användarnamn/lösenord?",
    SET_ORIGIN_URL:                     "Ange ursprungs-URL",
    SET_THIS_BRANCH_AS_TRACKING:        "Ställ in den här grenen som den nya spårningsgrenen",
    SHORTCUTS:                          "Genvägar",
    SHORTCUTS_HINT:                     "Separera tangenter med bindesträck, exempelvis: Ctrl-Alt-G<br>Du kan använda svenska tangent-modifierarna Ctrl, Cmd (Mac), Alt och Shift.",
    SHOWN_DATE_FORMAT:                  "Formatet för datum på commit-historiken",
    SHOW_BASH_TERMINAL_BUTTON:          "Visa Bash/Terminalknapp i panelen",
    SHOW_TERMINAL_IN_TOOLBAR:           "Visa Terminalikonen i verktygsfältet",
    SHOW_UNTRACKED:                     "Visa ospårade",
    STRIP_WHITESPACE_FROM_COMMITS:      "Ta bort extra blanksteg från commits",
    TARGET_BRANCH:                      "Mål-gren",
    TERMINAL_DISABLED:                  "Bash/Terminalkonsolen inaktiverad eftersom ingen giltig binär kune hittas",
    TITLE_CHECKOUT:                     "Vill du verkligen check-ut denna commit?",
    TITLE_RESET:                        "Vill du verkligen återställa?",
    TOOLTIP_CHECKOUT_COMMIT:            "Check-ut en specifik commit",
    TOOLTIP_CLONE:                      "Klona befintligt arkiv",
    TOOLTIP_CLOSE_NOT_MODIFIED:         "Stäng filer som inte har ändrats i Git [Shift-click för att visa ändrade filer igen]",
    TOOLTIP_COMMIT:                     "Commit de valda filerna",
    TOOLTIP_FETCH:                      "Hämta alla fjärr-arkiv och uppdatera räknare",
    TOOLTIP_FIND_CONFLICTS:             "Starter en sökning efter Git-sammanfognings- eller rebase-konflikter i det här projektet",
    TOOLTIP_GITPUSH:                    "Git-FTP Hämtning",
    TOOLTIP_HIDE_FILE_HISTORY:          "Dölj filhistorik",
    TOOLTIP_HIDE_HISTORY:               "Dölj historik",
    TOOLTIP_INIT:                       "Initiera arkivet",
    TOOLTIP_MERGE_ABORT:                "Avbryt sammanslagningen och återställa HEAD till den sista lokala commiten",
    TOOLTIP_MORE:                       "Fler åtgärder\u2026",
    TOOLTIP_OPEN_BASH:                  "Öppna Bash/Terminalkonsolen",
    TOOLTIP_PICK_REMOTE:                "Välj föredragen fjärr",
    TOOLTIP_PULL:                       "Git Pull",
    TOOLTIP_PUSH:                       "Git Push",
    TOOLTIP_REBASE_ABORT:               "Avbryt rebase åtgärden och återställ HEAD till orginal grenen",
    TOOLTIP_REBASE_CONTINUE:            "Starta om rebasing processen efter att ha löst en sammanfogningskonflikt",
    TOOLTIP_REBASE_SKIP:                "Starta om rebasing processen genom att skippa den nuvarande patchen",
    TOOLTIP_REFRESH_PANEL:              "Uppdatera panelen",
    TOOLTIP_SHOW_FILE_HISTORY:          "Visa filhistorik",
    TOOLTIP_SHOW_HISTORY:               "Visa historik",
    UNDO_CHANGES:                       "Kasta ändringarna",
    UNDO_LAST_LOCAL_COMMIT:             "Ångra den senaste lokala (inte upp-skickade) commiten",
    URL:                                "URL",
    USERNAME:                           "Användarnamn",
    USER_ABORTED:                       "Avbruten användaren!",
    USER_DATE_FORMAT:                   "Eget datum format (<a href='http://momentjs.com/docs/#/displaying/format/'>Syntax</a>)",
    USE_CODE_INSPECTION:                "Använd kodinspektion",
    USE_GITFTP:                         "Använd Git-FTP",
    USE_GIT_GUTTER:                     "Använd Git gutter markeringar",
    USE_NOFF:                           "Skapa en sammanfognings-commit, even om sammanfogningen resulterar i en fast-forward (--no-ff)",
    USE_REBASE:                         "Använd REBASE",
    USE_VERBOSE_DIFF:                   "Visa verbos-utskrift i differensen",
    USE_DIFFTOOL:                       "Använd difftool för differens",
    USING_GIT_VERSION:                  "Git version",
    VIEW_AUTHORS_FILE:                  "Visa filens författare",
    VIEW_AUTHORS_SELECTION:             "Visa författarna för urvalet",
    VIEW_THIS_FILE:                     "Visa den här filen",
    TAG_NAME_PLACEHOLDER:               "Ange ett taggnamn här\u2026",
    TAG_NAME:                           "Tagg"
});
