define({
    ACTION:                             "Åtgärd",
    ADD_ENDLINE_TO_THE_END_OF_FILE:     "Lägg till sluttecknen vid slutet av filen",
    ADD_TO_GITIGNORE:                   "Lägg till på .gitignore",
    ADVANCED_FEATURES_WARNING:          "Dessa funktioner är inte rekomenderade för standard Git användaren eftersom det finns en risk att du förlorar källkod som redan har lämnats över om funktionerna används felaktigt. Var försiktig.",
    AMEND_COMMIT:                       "Ändra senaste överlämningen",
    AMEND_COMMIT_FORBIDDEN:             "Kan inte ändra överlämningen eftersom det inte finns några knuffade att överlämna",
    _ANOTHER_BRANCH:                    "en annan gren",
    AUTHOR:                             "Författare",
    AUTHORS_OF:                         "Författare av",
    AVATAR_TYPE:                        "Avatartyp",
    BASH_NOT_AVAILABLE:                 "Bash är inte tillgängligt eller felaktigt inställd",
    BASIC_CONFIGURATION:                "Grundläggande konfigurering",
    BLACK_WHITE_AVATAR:                 "Svartvid avatar",
    BRACKETS_GIT_ERROR:                 "Brackets Git påträffat ett fel\u2026",
    BRANCH_NAME:                        "Förgreningsnamn",
    BUTTON_CANCEL:                      "Avbryt",
    BUTTON_CHANGELOG:                   "Visa ändringsloggen",
    BUTTON_CHECKOUT_COMMIT:             "Utforska",
    BUTTON_CLONE:                       "Klona",
    BUTTON_CLOSE:                       "Stäng",
    BUTTON_COMMIT:                      "Överlämna",
    BUTTON_DEFAULTS:                    "Återställ",
    BUTTON_FIND_CONFLICTS:              "Hitta konflikter\u2026",
    BUTTON_INIT:                        "Initsiera",
    BUTTON_MERGE_ABORT:                 "Avbryt sammanfogning",
    BUTTON_OK:                          "OK",
    BUTTON_REBASE_ABORT:                "Avstyr",
    BUTTON_REBASE_CONTINUE:             "Fortsätt med att omlokalisering",
    BUTTON_REBASE_SKIP:                 "Skippa",
    BUTTON_REPORT:                      "Rapport",
    BUTTON_RESET:                       "Återställ index",
    BUTTON_RESET_HARD:                  "Återställ denna överlämning och kasta alla ändringarna efter det. (reset --hard)",
    BUTTON_RESET_MIXED:                 "Återställ denna överlämning men behåll ändringarna efter som undangömda. (reset --mixed)",
    BUTTON_RESET_SOFT:                  "Återställ denna överlämning and behåll ändringarna efter som markerade för en ny överlämning. (reset --soft)",
    BUTTON_SAVE:                        "Spara",
    CANCEL:                             "Avbryt",
    CHANGELOG:                          "Ändŕingslogg",
    CHANGE_USER_EMAIL:                  "Ändra e-posten för Git",
    CHANGE_USER_NAME:                   "Ändra användarnamnet för Git",
    CHECK_GIT_SETTINGS:                 "Kunde inte starta git-binären - kontrollera git inställningarna och starta om Brackets",
    CLEAN_FILE_END:                     "Filer städade",
    CLEAN_FILE_START:                   "Städar filer",
    CLEANING_WHITESPACE_PROGRESS:       "Städa filer från blank-steg\u2026",
    CLEAR_WHITESPACE_ON_FILE_SAVE:      "Städa filer från blank-steg när filen sparas",
    CLONE_REPOSITORY:                   "Klona arkivet",
    CODE_INSPECTION_PROBLEMS:           "Fel vid källkodsinspektion:",
    COLLAPSE_ALL:                       "Fäll ihop alla",
    COLORED_AVATAR:                     "Avatarer i färg",
    COMMAND_ARGUMENTS:                  "Kommandotargument",
    COMMIT:                             "Överlämning",
    COMMIT_ALL_SHORTCUT:                "Överlämna alla filer",
    COMMIT_CURRENT_SHORTCUT:            "Lämna över nuvarande fil",
    COMMIT_MESSAGE_PLACEHOLDER:         "Skriv ett överlämnings-meddelande här\u2026",
    CREATE_NEW_BRANCH:                  "Skapa en ny gren\u2026",
    CREATE_NEW_GITFTP_SCOPE:            "Skapa ett ny Git-FTP fjärrarkiv\u2026",
    CREATE_NEW_REMOTE:                  "Skapa ett ny fjärrarkiv\u2026",
    CURRENT_TRACKING_BRANCH:            "Följer nuvarande gren",
    _CURRENT_TRACKING_BRANCH:           "följer nuvarande gren",
    CUSTOM_TERMINAL_COMMAND:            "Anpassat terminalkommando (exempel: gnome-terminal eller komplett sökväg till binär)",
    CUSTOM_TERMINAL_COMMAND_HINT:       "Exempel på argument: --window --working-directory=$1<br>$1 argumenten kommer att ersättas av den aktuella projektkatalogen.",
    DATE_FORMAT:                        "MM/DD/YYYY HH:mm:ss",
    DATE_MODE_0:                        "Formaterad med lokalt datumformat",
    DATE_MODE_1:                        "Relativ tid",
    DATE_MODE_2:                        "Intelligent läge (relativt / formaterat)",
    DATE_MODE_3:                        "Formaterad med ditt eget format",
    DATE_MODE_4:                        "Original Git-datum",
    DEBUG:                              "FELSÖK",
    DEBUG_MODE_SETTING:                 "Felsökningsläge &mdash; Lämna detta AV om du inte upplevcer ett problem med tillägget. All Git-kommunikation kommer att vidarebefordras till Brackets-konsolen!",
    DEFAULT_GIT_TIMEOUT:                "Standard-timeouten för Git-operation (i sekunder)",
    DELETE_FILE:                        "Ta bort fil",
    DELETE_LOCAL_BRANCH:                "Ta bort lokal gren",
    DELETE_LOCAL_BRANCH_NAME:           "Vill du verkligen ta bort den lokala grenen \"{0}\"?",
    DELETE_REMOTE:                      "Ta bort fjärrarkiv",
    DELETE_REMOTE_NAME:                 "Vill du verkligen ta bort ett fjärrarkiv \"{0}\"?",
    DELETE_SCOPE:                       "Radera Git-FTP-omfattning",
    DELETE_SCOPE_NAME:                  "Vill du verkligen ta bort Git-FTP-omfattning \"{0}\"?",
    DIALOG_CHECKOUT:                    "När du utforskar en överlämning kommer ditt repo att gå till ett DETACHED HUVUD-tillstånd. Du kan inte göra några överlämningar om du inte skapar en gren baserad på denna.",
    DIALOG_PULL_TITLE:                  "Drar från ett fjärrarkiv",
    DIALOG_PUSH_TITLE:                  "Knuffa till ett fjärrarkiv",
    DIALOG_RESET_HARD:                  "Du kommer förlorara alla ändringar efter denna överlämning!",
    DIALOG_RESET_MIXED:                 "Förändringar efter dena överlämning kommer bli omarkerade.",
    DIALOG_RESET_SOFT:                  "Förändringar efter dena överlämning kommer bli markerade för en ny överlämning.",
    DIFF:                               "Mellanskillnad",
    DIFFTOOL:                           "mellanskillnaden med difftool",
    DIFF_FAILED_SEE_FILES:              "Git kunde inte skapa en mellanskillnad på filerna. Detta är en lista över de markerade filer som kommer att överlämnas:",
    DIFF_TOO_LONG:                      "Mellanskillnad är för lång för att kunna visas",
    ENABLE_ADVANCED_FEATURES:           "Aktivera avancerade funktioner",
    ENABLE_GERRIT_PUSH_REF:             "Använd Gerrit-kompatibel knuff ref",
    ENTER_GITFTP_SCOPE_NAME:            "Ange namnet för den nya Git-FTP fjärrarkivet:",
    ENTER_GITFTP_SCOPE_URL:             "Ange FTP-URL för den nya Git-FTP fjärrarkivet ange både användarnamn och lösenord:",
    ENTER_NEW_USER_EMAIL:               "Ange e-postadress",
    ENTER_NEW_USER_NAME:                "Ange användarnamn",
    ENTER_PASSWORD:                     "Ange lösenord:",
    ENTER_REMOTE_GIT_URL:               "Ange en Git URL till det arkiv som du vill klona:",
    ENTER_REMOTE_NAME:                  "Ange ett namn för detta nya fjärrarkivetet:",
    ENTER_REMOTE_URL:                   "Ange en URL för detta nya fjärrarkivetet:",
    ENTER_USERNAME:                     "Ange användarnamn:",
    ERROR_CONNECT_NODEJS:               "Kunde inte ansluta till NodeJS. Om du nyligen har uppdaterat tillägget stänger du alla instanser av Brackets och försök starta igen. Om en omstart inte hjälper, försök då att ta bort andra tillägg som du har installerat eftersom något av dom förmodligen orsakar problem.",
    ERROR_NOTHING_SELECTED:             "Ingenting har markerats!",
    ERROR_SAVE_FIRST:                   "Spara dokumentet först!",
    ERROR_TERMINAL_NOT_FOUND:           "Terminalen hittades inte för ditt operativsystem, du kan definiera ett anpassat terminalkommando i inställningarna",
    EXPAND_ALL:                         "Expandera alla",
    EXTENDED_COMMIT_MESSAGE:            "UTÖKAD",
    EXTENSION_WAS_UPDATED_TITLE:        "Tillägget har uppdaterades till {0}",
    FEATURES:                           "Funktioner",
    FILE_ADDED:                         "Ny fil",
    FILE_COPIED:                        "Kopierad",
    FILE_DELETED:                       "Borttagen",
    FILE_IGNORED:                       "Ignored",
    FILE_MODIFIED:                      "Ändrad",
    FILE_RENAMED:                       "Omdöpt",
    FILE_STAGED:                        "Markerad",
    FILE_UNMERGED:                      "Ej sammanfogad",
    FILE_UNMODIFIED:                    "Oförändrad",
    FILE_UNTRACKED:                     "Spåras inte",
    FOR_MAC_LINUX_USERS:                "För Mac/Linux-användare",
    FOR_WINDOWS_USERS:                  "För Windows-användare",
    GETTING_STAGED_DIFF_PROGRESS:       "Hämtar mellanskillnaden av filer som är markerade\u2026",
    GITFTP_PUSH_RESPONSE:               "Git-FTP knuffa-svar",
    GITFTP_SCOPES:                      "Git-FTP fjärrarkiv",
    GIT_COMMIT:                         "Git överlämning\u2026",
    GIT_CONFIGURATION:                  "Git konfiguration",
    GIT_DIFF:                           "Git mellanskillnad &mdash;",
    GIT_PULL_RESPONSE:                  "Git drag-svar",
    GIT_PUSH_RESPONSE:                  "Git knuff-svar",
    GIT_REMOTES:                        "Git fjärrarkiv",
    GIT_SETTINGS:                       "Git inställningar\u2026",
    GOTO_NEXT_GIT_CHANGE:               "Gå till nästa Git-förändring",
    GOTO_PREVIOUS_GIT_CHANGE:           "Gå till tidigare Git-ändring",
    GUTTER_CLICK_DETAILS:               "Klicka för mer information",
    HIDE_UNTRACKED:                     "Dölj ospårade",
    HISTORY:                            "Historik",
    HISTORY_COMMIT_BY:                  "av",
    IDENTICON:                          "Identicon (www.gravatar.com)",
    INIT_GITFTP_SCOPE:                  "Initiera Git-FTP fjärrarkiv",
    INIT_GITFTP_SCOPE_NAME:             "Initiera Git-FTP fjärrarkiv \"{0}\"?",
    LAUNCH_BASH_SHORTCUT:               "Bash/Terminalgenväg",
    LINES:                              "Rader",
    _LINES:                             "rader",
    LIST_MODIFIED_FILES:                "Ändrade filer",
    LOADING:                            "Läser in\u2026",
    MARK_MODIFIED_FILES_IN_TREE:        "Markera ändrade filer i filträdet",
    MERGE_BRANCH:                       "Sammanfoga gren",
    MERGE_MESSAGE:                      "Sammanfogningsmeddelande",
    MERGE_RESULT:                       "Sammanfogningsresultat",
    MORE_INFO:                          "Mer information\u2026",
    NORMALIZE_LINE_ENDINGS:             "Normalisera linjeavslut (till \\n)",
    NOTHING_TO_COMMIT:                  "Inget att lämna över, arbetskatalogen är ren.",
    OK:                                 "OK",
    OPERATION_IN_PROGRESS_TITLE:        "Git-operation pågår\u2026",
    ORIGIN_BRANCH:                      "Ursprungs-gren",
    PANEL_COMMAND:                      "Visa Git panel",
    PANEL_SHORTCUT:                     "Växla panel",
    PASSWORD:                           "Lösenordet",
    PASSWORDS:                          "Lösenord",
    PATH_TO_GIT_EXECUTABLE:             "Sökväg till Git-binär",
    PATH_TO_GIT_MSYSGIT:                "Sökväg till msysgit-mapp",
    PICTURE:                            "Gravatar (www.gravatar.com)",
    PULL_AVOID_MERGING:                 "Undvik manuell sammansfogning",
    PULL_DEFAULT:                       "Standard-sammanfogning",
    PULL_FROM:                          "Dra från",
    PULL_MERGE_NOCOMMIT:                "Sammanfoga utan överlämning",
    PULL_REBASE:                        "Använd omlokalisering",
    PULL_RESET:                         "Använd mjuk återställning",
    PULL_SHORTCUT:                      "Dra hem från fjärrarkiv",
    PUSH_DEFAULT:                       "Standardknuff",
    PUSH_DELETE_BRANCH:                 "Ta bort fjärrarkiv",
    PUSH_SEND_TAGS:                     "Skicka med märkningar",
    PUSH_FORCED:                        "Forcera en knuff",
    PUSH_SHORTCUT:                      "Knuffa till fjärrarkiv",
    PUSH_TO:                            "Knuffa till",
    Q_DELETE_FILE:                      "Är du säker på att du vill ta bort filen <span class='dialog-filename'>{0}</span>?",
    Q_RESTART_BRACKETS:                 "Vill du starta om Brackets för att tillämpa de nya inställningarna?",
    Q_UNDO_CHANGES:                     "Återställ ändringar på filen <span class='dialog-filename'>{0}</span>?",
    REBASE_RESULT:                      "Resultatet av omlokalisera",
    REFRESH_GIT:                        "Förnya Git",
    REMOVE_BOM:                         "Ta bort BOM från filer",
    REMOVE_FROM_GITIGNORE:              "Ta bort från .gitignore",
    REQ_INTERNET:                       "Kräver internetuppkoppling",
    RESET_LOCAL_REPO:                   "Återställ alla ändringar sedan senaste överlämningen",
    RESET_LOCAL_REPO_CONFIRM:           "Vill du kasta alla ändringar som gjorts sedan den senaste överlämningen? Denna åtgärden kan inte återställas.",
    RESTART:                            "Omstart",
    SAVE_CREDENTIALS_HELP:              "Du behöver inte fylla i användarnamn / lösenord om dina uppgifter hanteras någon annanstans. Använd endast detta när din åtgärder fortsätter att gå fel.",
    SAVE_CREDENTIALS_IN_URL:            "Spara dina uppgifter till fjärr-url (i klartext)",
    SAVE_PASSWORD_QUESTION:             "Spara användarnamn/lösenord?",
    SET_ORIGIN_URL:                     "Ange ursprungs-URL",
    SET_THIS_BRANCH_AS_TRACKING:        "Ställ in den här grenen som den nya spårningsgrenen",
    SHORTCUTS:                          "Genvägar",
    SHORTCUTS_HINT:                     "Separera tangenter med bindesträck, exempelvis: Ctrl-Alt-G<br>Du kan använda svenska tangent-modifierarna Ctrl, Cmd (Mac), Alt och Shift.",
    SHOWN_DATE_FORMAT:                  "Formatet för datum på commit-historiken",
    SHOW_BASH_TERMINAL_BUTTON:          "Visa Bash/Terminalknapp i panelen",
    SHOW_TERMINAL_IN_TOOLBAR:           "Visa Terminalikonen i verktygsfältet",
    SHOW_UNTRACKED:                     "Visa ospårade",
    STRIP_WHITESPACE_FROM_COMMITS:      "Ta bort extra blanksteg från överlämningar",
    TARGET_BRANCH:                      "Målgren",
    TERMINAL_DISABLED:                  "Bash/Terminalkonsolen inaktiverad eftersom ingen giltig binär kune hittas",
    TITLE_CHECKOUT:                     "Vill du verkligen utforska denna överlämning?",
    TITLE_RESET:                        "Vill du verkligen återställa?",
    TOOLTIP_CHECKOUT_COMMIT:            "Utforska en specifik överlämning",
    TOOLTIP_CLONE:                      "Klona befintligt arkiv",
    TOOLTIP_CLOSE_NOT_MODIFIED:         "Stäng filer som inte har ändrats i Git [Shift-click för att visa ändrade filer igen]",
    TOOLTIP_COMMIT:                     "Överlämna de valda filerna",
    TOOLTIP_FETCH:                      "Hämta alla fjärrarkiv och uppdatera räknare",
    TOOLTIP_FIND_CONFLICTS:             "Starter en sökning efter sammanfognings- eller omlokaliserings-konflikter i det här projektet",
    TOOLTIP_GITPUSH:                    "Git-FTP knuff",
    TOOLTIP_HIDE_FILE_HISTORY:          "Dölj filhistorik",
    TOOLTIP_HIDE_HISTORY:               "Dölj historik",
    TOOLTIP_INIT:                       "Initiera arkivet",
    TOOLTIP_MERGE_ABORT:                "Avbryt sammanfogningen och återställa HUVUDET till den sista lokala överlämningen",
    TOOLTIP_MORE:                       "Fler åtgärder\u2026",
    TOOLTIP_OPEN_BASH:                  "Öppna Bash/Terminalkonsolen",
    TOOLTIP_PICK_REMOTE:                "Välj föredraget fjärrarkiv",
    TOOLTIP_PULL:                       "Git Dra",
    TOOLTIP_PUSH:                       "Git Knuff",
    TOOLTIP_REBASE_ABORT:               "Avbryt omlokaliseringen och återställ HUVET till ursprungsgrenen",
    TOOLTIP_REBASE_CONTINUE:            "Starta om omlokaliseringen efter att sammanfogningskonflikt är löst",
    TOOLTIP_REBASE_SKIP:                "Starta om omlokaliseringen genom att skippa den nuvarande patchen",
    TOOLTIP_REFRESH_PANEL:              "Uppdatera panelen",
    TOOLTIP_SHOW_FILE_HISTORY:          "Visa filhistorik",
    TOOLTIP_SHOW_HISTORY:               "Visa historik",
    UNDO_CHANGES:                       "Kasta ändringarna",
    UNDO_LAST_LOCAL_COMMIT:             "Ångra den senaste lokala (inte redan knuffade) överlämningen",
    URL:                                "URL",
    USERNAME:                           "Användarnamn",
    USER_ABORTED:                       "Avbruten användaren!",
    USER_DATE_FORMAT:                   "Eget datum format (<a href='http://momentjs.com/docs/#/displaying/format/'>Syntax</a>)",
    USE_CODE_INSPECTION:                "Använd kodinspektion",
    USE_GITFTP:                         "Använd Git-FTP",
    USE_GIT_GUTTER:                     "Använd Git gutter markeringar",
    USE_NOFF:                           "Skapa en sammanfogningsöverlämning, even om sammanfogningen resulterar i en fast-forward (--no-ff)",
    USE_REBASE:                         "Använd OMLOKALISERING",
    USE_VERBOSE_DIFF:                   "Visa verbos-utskrift i mellanskillnad",
    USE_DIFFTOOL:                       "Använd difftool för mellanskillnad",
    USING_GIT_VERSION:                  "Git version",
    VIEW_AUTHORS_FILE:                  "Visa filens författare",
    VIEW_AUTHORS_SELECTION:             "Visa författarna för urvalet",
    VIEW_THIS_FILE:                     "Visa den här filen",
    TAG_NAME_PLACEHOLDER:               "Ange ett märknamn här\u2026",
    TAG_NAME:                           "Märke"
});
