/*global define */

define({
    BRACKETS_GIT_ERROR:                 "Brackets Git 遇到了一个错误\u2026",
    BUTTON_BUG_REPORT:                  "报告问题\u2026",
    BUTTON_CANCEL:                      "取消",
    BUTTON_CHANGELOG:                   "显示更改（Changelog）",
    BUTTON_CLOSE:                       "关闭",
    BUTTON_CLOSE_NOT_MODIFIED:          "关闭未被修改的文件",
    BUTTON_COMMIT:                      "提交",
    BUTTON_DEFAULTS:                    "重置默认值",
    BUTTON_HIDE_UNTRACKED:              "隐藏未被跟踪文件",
    BUTTON_SHOW_UNTRACKED:              "显示未被跟踪文件",
    BUTTON_INIT:                        "初始化Git仓库",
    BUTTON_OK:                          "确认",
    BUTTON_PULL:                        "Git Pull",
    BUTTON_PUSH:                        "Git Push",
    BUTTON_REPORT:                      "报告错误",
    BUTTON_RESET:                       "重置当前更改",
    BUTTON_SAVE:                        "保存",
    CHANGELOG:                          "更改记录（Changelog）",
    CHECK_GIT_SETTINGS:                 "检查 Git 设置",
    COMMIT_MESSAGE_PLACEHOLDER:         "在此编辑提交信息\u2026",
    DELETE_FILE:                        "删除文件",
    DIFF:                               "运行 Diff 查看更改",
    EXTENSION_WAS_UPDATED_TITLE:        "扩展已经更新到 {0} 版本",
    FEATURE_SETTINGS:                   "特性设置",
    FILE_DELETED:                       "已删除",
    FILE_MODIFIED:                      "已修改",
    FILE_NEWFILE:                       "新加入",
    FILE_STAGED:                        "被跟踪的文件",
    FILE_UNTRACKED:                     "未被跟踪的文件",
    FILE_RENAMED:                       "重命名",
    FOR_WINDOWS_USERS:                  "对于 Windows 用户",
    GIT_COMMIT:                         "Git commit\u2026",
    GIT_DIFF:                           "Git diff &mdash;",
    GIT_IS_IN_PATH:                     "Git 可以在直接调用 (即在系统路径内，对 Mac 可能无效)",
    GIT_PULL_RESPONSE:                  "Git Pull 的回应",
    GIT_PUSH_RESPONSE:                  "Git Push 的回应",
    GIT_SETTINGS:                       "Git 设置\u2026",
    LOADING:                            "加载中\u2026",
    NOTHING_TO_COMMIT:                  "没有更改，不需要提交。",
    PATH_TO_GIT_EXECUTABLE:             "Git 执行文件路径",
    PATH_TO_GIT_MSYSGIT:                "msysgit 的路径",
    PANEL_COMMAND:                      "Git 面板",
    Q_DELETE_FILE:                      "你确认要删除 {0} 文件吗？",
    Q_RESTART_BRACKETS:                 "希望现在重启 Brackets 并应用更改吗？",
    Q_UNDO_CHANGES:                     "确认重置对 {0} 文件的更改？",
    RESTART:                            "重新启动",
    STRIP_WHITESPACE_FROM_COMMITS:      "去除提交信息后的空白字符",
    UNDO_CHANGES:                       "撤销更改",
    USING_GIT_VERSION:                  "Git 版本"
});
