/*global define */

define({
    ADD_ENDLINE_TO_THE_END_OF_FILE:     "Adicionar endline no fim do arquivo",
    ADD_TO_GITIGNORE:                   "Adicionar ao .gitignore",
    REMOVE_FROM_GITIGNORE:              "Remover do .gitignore",
    BRACKETS_GIT_ERROR:                 "Brackets Git encontrou um erro\u2026",
    BRANCH_NAME:                        "Nome do Branch",
    BUTTON_BUG_REPORT:                  "Relatar erro",
    BUTTON_CANCEL:                      "Cancelar",
    BUTTON_CHANGELOG:                   "Histórico de alterações",
    BUTTON_CLOSE:                       "Fechar",
    BUTTON_CLOSE_NOT_MODIFIED:          "Fechar não modificados",
    BUTTON_COMMIT:                      "Fazer Commit",
    BUTTON_DEFAULTS:                    "Restaurar padrões",
    BUTTON_HIDE_UNTRACKED:              "Ocultar untracked",
    BUTTON_SHOW_UNTRACKED:              "Mostrar untracked",
    BUTTON_INIT:                        "Init",
    BUTTON_OK:                          "OK",
    BUTTON_PULL:                        "Git Pull",
    BUTTON_PUSH:                        "Git Push",
    BUTTON_REPORT:                      "Relatar",
    BUTTON_RESET:                       "Resetar índice",
    BUTTON_SAVE:                        "Salvar",
    CHANGELOG:                          "Histórico de alterações",
    CHECK_GIT_SETTINGS:                 "Verificar configurações do Git",
    COMMIT_MESSAGE_PLACEHOLDER:         "Insira a mensagem do commit aqui\u2026",
    CREATE_NEW_BRANCH:                  "Criar um novo branch\u2026",
    DELETE_FILE:                        "Excluir arquivo",
    DIFF:                               "Diff",
    EXTENSION_WAS_UPDATED_TITLE:        "A extensão foi atualizada para {0}",
    FEATURE_SETTINGS:                   "Configurações de recursos",
    FILE_DELETED:                       "Exluído",
    FILE_MODIFIED:                      "Modificado",
    FILE_NEWFILE:                       "Novo arquivo",
    FILE_STAGED:                        "Staged",
    FILE_UNTRACKED:                     "Untracked",
    FILE_RENAMED:                       "Renomeado",
    FOR_WINDOWS_USERS:                  "Para usuários de Windows",
    GIT_COMMIT:                         "Git commit\u2026",
    GIT_DIFF:                           "Git diff &mdash;",
    GIT_IS_IN_PATH:                     "O Git pode ser usado de qualquer lugar (está no caminho do sistema, pode não funcionar no Mac)",
    GIT_PULL_RESPONSE:                  "Resposta do Git Pull",
    GIT_PUSH_RESPONSE:                  "Resposta do Git Push",
    GIT_SETTINGS:                       "Configurações do Git\u2026",
    LOADING:                            "Carregando\u2026",
    NOTHING_TO_COMMIT:                  "Nada para fazer commit, diretório de trabalho limpo.",
    PATH_TO_GIT_EXECUTABLE:             "Caminho para executável do Git",
    PATH_TO_GIT_MSYSGIT:                "Caminho para pasta do msysgit",
    PANEL_COMMAND:                      "Git",
    Q_DELETE_FILE:                      "Tem certeza de que deseja excluir o arquivo {0}?",
    Q_RESTART_BRACKETS:                 "Deseja reiniciar o Brackets para aplicar as novas configurações?",
    Q_UNDO_CHANGES:                     "Redefinir alterações ao arquivo {0}?",
    RESTART:                            "Reiniciar",
    SET_ORIGIN_URL:                     "Definir URL da origem",
    STRIP_WHITESPACE_FROM_COMMITS:      "Remover espaços em branco extras dos commits",
    UNDO_CHANGES:                       "Desfazer alterações",
    URL:                                "URL",
    USE_GIT_GUTTER:                     "Usar marcas do Git na margem",
    USING_GIT_VERSION:                  "Versão do Git"
});