/*jshint maxlen:false */

define({
    ADD_ENDLINE_TO_THE_END_OF_FILE:     "Adicionar endline no fim do arquivo",
    ADD_TO_GITIGNORE:                   "Adicionar ao .gitignore",
    AGREE_TO_STORE_PASSWORDS:           "Concordo com que a senha será armazenada como um texto simples no meu computador",
    AMEND_COMMIT:                       "Emendar no último commit",
    AMEND_COMMIT_FORBIDDEN:             "Não é possível emendar o commit quando não tem unpushed commits",
    BASH_NOT_AVAILABLE:                 "O console de comando não está disponível ou propriamente configurado",
    BASIC_CONFIGURATION:                "Configuração básica",
    BRACKETS_GIT_ERROR:                 "Brackets Git encontrou um erro\u2026",
    BRANCH_NAME:                        "Nome do Branch",
    BUTTON_CANCEL:                      "Cancelar",
    BUTTON_CHANGELOG:                   "Histórico de alterações",
    BUTTON_CLOSE:                       "Fechar",
    BUTTON_DEFAULTS:                    "Restaurar padrões",
    BUTTON_OK:                          "OK",
    BUTTON_REPORT:                      "Relatar",
    BUTTON_SAVE:                        "Salvar",
    BUTTON_COMMIT:                      "Fazer Commit",
    BUTTON_INIT:                        "Init",
    CHANGELOG:                          "Histórico de alterações",
    CHECK_GIT_SETTINGS:                 "Verificar configurações do Git",
    COMMIT_ALL_SHORTCUT:                "Commit todos os arquivos",
    COMMIT_CURRENT_SHORTCUT:            "Commit arquivo atual",
    COMMIT_MESSAGE_PLACEHOLDER:         "Insira a mensagem do commit aqui\u2026",
    CREATE_NEW_BRANCH:                  "Criar um novo branch\u2026",
    CUSTOM_TERMINAL_COMMAND:            "Custom terminal command (sample: gnome-terminal --window --working-directory=$1)",
    DELETE_FILE:                        "Excluir arquivo",
    DIFF:                               "Diff",
    ENTER_PASSWORD:                     "Senha",
    ENTER_USERNAME:                     "Usuário",
    ERROR_TERMINAL_NOT_FOUND:           "Terminal was not found for your OS, you can define a custom Terminal command in the settings",
    EXTENSION_WAS_UPDATED_TITLE:        "A extensão foi atualizada para {0}",
    FEATURES:                           "Recursos",
    FILE_DELETED:                       "Exluído",
    FILE_MODIFIED:                      "Modificado",
    FILE_NEWFILE:                       "Adicionado",
    FILE_RENAMED:                       "Renomeado",
    FILE_STAGED:                        "Staged",
    FILE_UNTRACKED:                     "Untracked",
    FOR_MAC_LINUX_USERS:                "Para usuários de Mac/Linux",
    FOR_WINDOWS_USERS:                  "Para usuários de Windows",
    GIT_COMMIT:                         "Git commit\u2026",
    GIT_DIFF:                           "Git diff &mdash;",
    GIT_IS_IN_PATH:                     "O Git pode ser usado de qualquer lugar (está no caminho do sistema, pode não funcionar no Mac)",
    GIT_PULL_RESPONSE:                  "Resposta do Git Pull",
    GIT_PUSH_RESPONSE:                  "Resposta do Git Push",
    GIT_SETTINGS:                       "Configurações do Git\u2026",
    LOADING:                            "Carregando\u2026",
    LIST_MODIFIED_FILES:                "Lista de arquivos modificados",
    MARK_MODIFIED_FILES_IN_TREE:        "Marcar arquivos modificados na árvore de arquivos",
    NOTHING_TO_COMMIT:                  "Nada para fazer commit, diretório de trabalho limpo.",
    PANEL_COMMAND:                      "Git",
    PANEL_SHORTCUT:                     "Toggle panel",
    PASSWORDS:                          "Senhas",
    PATH_TO_GIT_EXECUTABLE:             "Caminho para executável do Git",
    PATH_TO_GIT_MSYSGIT:                "Caminho para pasta do msysgit",
    Q_DELETE_FILE:                      "Tem certeza de que deseja excluir o arquivo <span class='dialog-filename'>{0}</span>?",
    Q_RESTART_BRACKETS:                 "Deseja reiniciar o Brackets para aplicar as novas configurações?",
    Q_UNDO_CHANGES:                     "Redefinir alterações ao arquivo <span class='dialog-filename'>{0}</span>?",
    REMOVE_FROM_GITIGNORE:              "Remover do .gitignore",
    RESTART:                            "Reiniciar",
    SAVE_PASSWORD_QUESTION:             "Salvar usuário/senha?",
    SET_ORIGIN_URL:                     "Definir URL da origem",
    STRIP_WHITESPACE_FROM_COMMITS:      "Remover espaços em branco extras dos commits",
    TOOLTIP_BUG:                        "Relatar erro",
    TOOLTIP_OPEN_BASH:                  "Abrir console de comandos",
    TOOLTIP_PULL:                       "Git Pull",
    TOOLTIP_PUSH:                       "Git Push",
    TOOLTIP_CLOSE_NOT_MODIFIED:         "Fechar não modificados",
    TOOLTIP_INIT:                       "Inicializar repositório",
    TOOLTIP_COMMIT:                     "Fazer Commit dos arquivos selecionados",
    TOOLTIP_SHOW_UNTRACKED:             "Mostrar untracked",
    TOOLTIP_HIDE_UNTRACKED:             "Ocultar untracked",
    TOOLTIP_REFRESH_PANEL:              "Recarregar painel",
    TOOLTIP_HISTORY:                    "Histórico",
    UNDO_CHANGES:                       "Desfazer alterações",
    URL:                                "URL",
    USE_CODE_INSPECTION:                "Usar inspetor de código",
    USE_GIT_GUTTER:                     "Usar marcas do Git na margem",
    USING_GIT_VERSION:                  "Versão do Git"
});
