define({
    ACTION:                             "Czynność",
    ADD_ENDLINE_TO_THE_END_OF_FILE:     "Dodaj linię na końcu pliku",
    ADD_TO_GITIGNORE:                   "Dodaj do .gitignore",
    ADVANCED_FEATURES_WARNING:          "Te funkcje nie są rekomendowane dla podstawowych użytkowników Gita, ponieważ mogą one spowodować utratę kodu, który jest już zcommitowany jeśli są używane nieodpowiednio. Używaj z ostrożnością.",
    AMEND_COMMIT:                       "Popraw ostatni commit",
    AMEND_COMMIT_FORBIDDEN:             "Nie można poprawić commitu kiedy są niewgrane commity",
    _ANOTHER_BRANCH:                    "inny branch",
    AUTHOR:                             "Autor",
    AUTHORS_OF:                         "Autorzy",
    AVATAR_TYPE:                        "Typ awatara",
    BASH_NOT_AVAILABLE:                 "Bash nie jest dostępny lub odpowiednio skonfigurowany",
    BASIC_CONFIGURATION:                "Podstawowa konfiguracja",
    BLACK_WHITE_AVATAR:                 "Czarno-biały awatar",
    BRACKETS_GIT_ERROR:                 "Brackets Git napotkał błąd\u2026",
    BRANCH_NAME:                        "Nazwa brancha",
    BUTTON_CANCEL:                      "Anuluj",
    BUTTON_CHANGELOG:                   "Pokaż logi zmian",
    BUTTON_CHECKOUT_COMMIT:             "Checkout",
    BUTTON_CLONE:                       "Klonuj",
    BUTTON_CLOSE:                       "Zamknij",
    BUTTON_COMMIT:                      "Commit",
    BUTTON_DEFAULTS:                    "Przywróć domyślne",
    BUTTON_FIND_CONFLICTS:              "Znajdź konflikty\u2026",
    BUTTON_INIT:                        "Inicjuj",
    BUTTON_MERGE_ABORT:                 "Przerwij mergowanie",
    BUTTON_OK:                          "OK",
    BUTTON_REBASE_ABORT:                "Przerwij",
    BUTTON_REBASE_CONTINUE:             "Kontynuuj rebase",
    BUTTON_REBASE_SKIP:                 "Pomiń",
    BUTTON_REPORT:                      "Zgłoś",
    BUTTON_RESET:                       "Resetuj index",
    BUTTON_RESET_HARD:                  "Resetuj do tego commita i usuń zmiany, które były po nim. (reset --hard)",
    BUTTON_RESET_MIXED:                 "Resetuj do tego commita i zatrzymaj zmiany, które były po nim niezgłoszone do commitu. (reset --mixed)",
    BUTTON_RESET_SOFT:                  "Resetuj do tego commita i zatrzymaj zmiany, które były po nim zgłoszone do nowego commitu. (reset --soft)",
    BUTTON_SAVE:                        "Zapisz",
    CANCEL:                             "Anuluj",
    CHANGELOG:                          "Plik zmian",
    CHANGE_USER_EMAIL:                  "Zmień email gita",
    CHANGE_USER_NAME:                   "Zmień nazwę gita",
    CHECK_GIT_SETTINGS:                 "Nie udało się uruchomić Gita - napraw ustawienia Gita i zrestartuj Brackets",
    CLEAN_FILE_END:                     "Plik wyczyszczony",
    CLEAN_FILE_START:                   "Czyszczenie pliku",
    CLEANING_WHITESPACE_PROGRESS:       "Czyszczenie białych znaków z plików\u2026",
    CLEAR_WHITESPACE_ON_FILE_SAVE:      "Czyść białe znaki podczas zapisu pliku",
    CLONE_REPOSITORY:                   "Klonuj repozytorium",
    CODE_INSPECTION_PROBLEMS:           "Problemy inspekcji kodu:",
    COLLAPSE_ALL:                       "Zwiń wszystko",
    COLORED_AVATAR:                     "Kolorowy awatar",
    COMMAND_ARGUMENTS:                  "Argumenty polecenia",
    COMMIT:                             "Commituj",
    COMMIT_ALL_SHORTCUT:                "Commituj wszystkie pliki",
    COMMIT_CURRENT_SHORTCUT:            "Commituj aktualny plik",
    COMMIT_MESSAGE_PLACEHOLDER:         "Wstaw wiadomość commita tutaj\u2026",
    CREATE_NEW_BRANCH:                  "Utwórz nowy branch\u2026",
    CREATE_NEW_GITFTP_SCOPE:            "Utwórz nowy Git-FTP remote\u2026",
    CREATE_NEW_REMOTE:                  "Utwórzy nowy remote\u2026",
    CURRENT_TRACKING_BRANCH:            "Aktualnie śledzony branch",
    _CURRENT_TRACKING_BRANCH:           "aktualnie śledzony branch",
    CUSTOM_TERMINAL_COMMAND:            "Niestandardowa komenda terminalu (przykład: gnome-terminal lub pełna ścieżka do pliku wykonywalnego)",
    CUSTOM_TERMINAL_COMMAND_HINT:       "Przykładowe argumenty: --window --working-directory=$1<br>$1 w argumentach jest zamieniane na katalog aktualnego projektu.",
    DATE_FORMAT:                        "MM/DD/YYYY HH:mm:ss",
    DATE_MODE_0:                        "Formatowane używając lokalnego formatu daty",
    DATE_MODE_1:                        "Czas relatywny",
    DATE_MODE_2:                        "Tryb inteligentny (relatywny/sformatowany)",
    DATE_MODE_3:                        "Sformatowane używając Twojego własnego formatu",
    DATE_MODE_4:                        "Oryginalna data Gita",
    DEBUG:                              "Debug",
    DEBUG_MODE_SETTING:                 "Tryb DEBUG &mdash; Zostaw go WYŁĄCZONEGO jeżeli nie potrzebujesz znaleźć problemu z rozszerzeniem. Cała komunikacja Gita będzie przekazywana do konsoli Brackets!",
    DEFAULT_GIT_TIMEOUT:                "Domyślny timeout operacji Gita (w sekundach)",
    DELETE_FILE:                        "Usuń plik",
    DELETE_LOCAL_BRANCH:                "Usuń lokalny branch",
    DELETE_LOCAL_BRANCH_NAME:           "Naprawdę chcesz usunąć lokalny branch \"{0}\"?",
    DELETE_REMOTE:                      "Usuń remote",
    DELETE_REMOTE_NAME:                 "Naprawdę chcesz usunąć remote \"{0}\"?",
    DELETE_SCOPE:                       "Usuń Git-FTP scope",
    DELETE_SCOPE_NAME:                  "Naprawdę chcesz usunąć Git-FTP scope \"{0}\"?",
    DIALOG_CHECKOUT:                    "Podczas checkouta commita, repo pójdzie do stanu DETACHED HEAD. Nie możesz zrobić żadnych commitów jeżeli nie utworzysz brancha bazującego na tym.",
    DIALOG_PULL_TITLE:                  "Pull z remote",
    DIALOG_PUSH_TITLE:                  "Push do remote",
    DIALOG_RESET_HARD:                  "Stracisz wszystkie zmiany po tym commicie!",
    DIALOG_RESET_MIXED:                 "Zmiany po tym commicie będą w fazie unstaged.",
    DIALOG_RESET_SOFT:                  "Zmiany po tym commicie będą w fazie staged dla nowego commita.",
    DIFF:                               "Diff",
    DIFFTOOL:                           "Diff z difftoolem",
    DIFF_FAILED_SEE_FILES:              "Git diff nie udało się dostarczyć wyników diff. To jest lista plików w fazie staged czekających na commit:",
    DIFF_TOO_LONG:                      "Diff za długi do wyświetlenia",
    ENABLE_ADVANCED_FEATURES:           "Włącz zaawansowane funkcjonalności",
    ENABLE_GERRIT_PUSH_REF:             "Używaj push ref kompatybilny z Gerritem",
    ENTER_GITFTP_SCOPE_NAME:            "Wpisz nazwę nowego Git-FTP remote:",
    ENTER_GITFTP_SCOPE_URL:             "Wpisz URL FTP nowego Git-FTP remote specyfikując nazwę użytkownika i hasło:",
    ENTER_NEW_USER_EMAIL:               "Wpisz email",
    ENTER_NEW_USER_NAME:                "Wpisz nazwę użytkownika",
    ENTER_PASSWORD:                     "Wpisz hasło:",
    ENTER_REMOTE_GIT_URL:               "Wpisz URL Gita repozytorium, które chcesz sklonować:",
    ENTER_REMOTE_NAME:                  "Wpisz nazwę nowego remote:",
    ENTER_REMOTE_URL:                   "Wpisz URL nowego remote:",
    ENTER_USERNAME:                     "Wpisz nazwę użytkownika:",
    ERROR_CONNECT_NODEJS:               "Nie udało się połączyć z NodeJS. Jeśli właśnie aktualizowałeś rozszerzenie to zamknij wszystkie instancje Brackets i spróbuj ponownie. Jeśli restart nie pomoże spróbuj usuwając inne rozszerzenia, które zainstalowałeś, ponieważ mogą być powodem tego problemu.",
    ERROR_NOTHING_SELECTED:             "Nic nie jest zaznaczone!",
    ERROR_SAVE_FIRST:                   "Najpierw zapisz dokument!",
    ERROR_TERMINAL_NOT_FOUND:           "Terminal nie został znaleziony dla Twojego systemu, możesz zdefiniować niestandardowy terminal w ustawieniach",
    EXPAND_ALL:                         "Rozwiń wszystko",
    EXTENDED_COMMIT_MESSAGE:            "EXTENDED",
    EXTENSION_WAS_UPDATED_TITLE:        "Rozszerzenie zostało zaktualizowane do {0}",
    FEATURES:                           "Cechy",
    FILE_ADDED:                         "Nowy plik",
    FILE_COPIED:                        "Skopiowany",
    FILE_DELETED:                       "Usunięty",
    FILE_IGNORED:                       "Zignorowany",
    FILE_MODIFIED:                      "Zmodyfikowany",
    FILE_RENAMED:                       "Zmieniona nazwa",
    FILE_STAGED:                        "Faza staged",
    FILE_UNMERGED:                      "Faza unmerged",
    FILE_UNMODIFIED:                    "Niezmodyfikowany",
    FILE_UNTRACKED:                     "Faza Untracked",
    FOR_MAC_LINUX_USERS:                "Tylko dla użytkowników Maca/Linuxa",
    FOR_WINDOWS_USERS:                  "Tylko dla użytkowników Windowsa",
    GETTING_STAGED_DIFF_PROGRESS:       "Pobieranie diff z plików w fazie staged\u2026",
    GITFTP_PUSH_RESPONSE:               "Odpowiedź Git-FTP push",
    GITFTP_SCOPES:                      "Git-FTP remotes",
    GIT_COMMIT:                         "Git commit\u2026",
    GIT_CONFIGURATION:                  "Konfiguracja Gita",
    GIT_DIFF:                           "Git diff &mdash;",
    GIT_PULL_RESPONSE:                  "Odpowiedź Git pull",
    GIT_PUSH_RESPONSE:                  "Odpowiedź Git push",
    GIT_REMOTES:                        "Git remotes",
    GIT_SETTINGS:                       "Ustawienia Gita\u2026",
    GOTO_NEXT_GIT_CHANGE:               "Idź do następnej zmiany Gita",
    GOTO_PREVIOUS_GIT_CHANGE:           "Idź do poprzedniej zmiany Gita",
    GUTTER_CLICK_DETAILS:               "Naciśnij, aby uzyskać szczegóły",
    HIDE_UNTRACKED:                     "Ukryj untracked",
    HISTORY:                            "Historia",
    HISTORY_COMMIT_BY:                  "przez",
    IDENTICON:                          "Identicon (www.gravatar.com)",
    INIT_GITFTP_SCOPE:                  "Inicjalizuj Git-FTP remote",
    INIT_GITFTP_SCOPE_NAME:             "Inicjalizuj Git-FTP remote \"{0}\"?",
    LAUNCH_BASH_SHORTCUT:               "Skrót Bash/Terminal",
    LINES:                              "Linii",
    _LINES:                             "linii",
    LIST_MODIFIED_FILES:                "Zmodyfikowane pliki",
    LOADING:                            "Ładowanie\u2026",
    MARK_MODIFIED_FILES_IN_TREE:        "Zaznacz zmodyfikowane pliki w drzewie plików",
    MERGE_BRANCH:                       "Merguj branch",
    MERGE_MESSAGE:                      "Wiadomość mergowania",
    MERGE_RESULT:                       "Wynik mergowania",
    MORE_INFO:                          "Więcej informacji\u2026",
    NORMALIZE_LINE_ENDINGS:             "Normalizuj końce linii (do \\n)",
    NOTHING_TO_COMMIT:                  "Nic do zcommitowania, katalog roboczy czysty.",
    OK:                                 "OK",
    OPERATION_IN_PROGRESS_TITLE:        "Operacja Gita w trakcie\u2026",
    ORIGIN_BRANCH:                      "Początkowy branch",
    PANEL_COMMAND:                      "Pokaż panel Gita",
    PANEL_SHORTCUT:                     "Przełącz panel",
    PASSWORD:                           "Hasło",
    PASSWORDS:                          "Hasła",
    PATH_TO_GIT_EXECUTABLE:             "Ścieżka do Gita",
    PATH_TO_GIT_MSYSGIT:                "Ścieżka do katalogu msysgit",
    PICTURE:                            "Gravatar (www.gravatar.com)",
    PULL_AVOID_MERGING:                 "Unikaj manualnego mergowania",
    PULL_DEFAULT:                       "Domyślny merge",
    PULL_FROM:                          "Pull z",
    PULL_MERGE_NOCOMMIT:                "Merguj bez commita",
    PULL_REBASE:                        "Użyj rebase",
    PULL_RESET:                         "Użyj soft reset",
    PULL_SHORTCUT:                      "Pull ze zdalnego repozytorium",
    PUSH_DEFAULT:                       "Domyślny push",
    PUSH_DELETE_BRANCH:                 "Usuń remote branch",
    PUSH_SEND_TAGS:                     "Wyślij tagi",
    PUSH_FORCED:                        "Wymuszony push",
    PUSH_SHORTCUT:                      "Push do zdalnego repozytorium",
    PUSH_TO:                            "Push do",
    Q_DELETE_FILE:                      "Czy naprawdę chcesz usunąć plik <span class='dialog-filename'>{0}</span>?",
    Q_RESTART_BRACKETS:                 "Chcesz zrestartować Brackets, aby zatwierdzić nowe ustawienia?",
    Q_UNDO_CHANGES:                     "Cofnąć zmiany do pliku <span class='dialog-filename'>{0}</span>?",
    REBASE_RESULT:                      "Wyniki rebase",
    REFRESH_GIT:                        "Odśwież Git",
    REMOVE_BOM:                         "Usuń BOM z plików",
    REMOVE_FROM_GITIGNORE:              "Usuń z .gitignore",
    REQ_INTERNET:                       "Wymaga połączenia internetowego",
    RESET_LOCAL_REPO:                   "Porzuć wszystkie zmiany od ostatniego commitu",
    RESET_LOCAL_REPO_CONFIRM:           "Naprawdę chcesz porzucić wszystkie zmiany wykonane od ostatniego commitu? Ta czynność nie może być cofnięta.",
    RESTART:                            "Restart",
    SAVE_CREDENTIALS_HELP:              "Nie musisz wypełniać nazwy użytkownika/hasła jeśli Twoje dane są zarządzane gdzie indziej. Użyj tego tylko kiedy Twoja operacja trwa za długo.",
    SAVE_CREDENTIALS_IN_URL:            "Zapisz dane logowania do zdalnego url (w prostym pliku tekstowym)",
    SAVE_PASSWORD_QUESTION:             "Zapisać nazwę użytkownika/hasło?",
    SET_ORIGIN_URL:                     "Ustaw początkowy URL",
    SET_THIS_BRANCH_AS_TRACKING:        "Ustaw ten branch jako nowy tracking branch",
    SHORTCUTS:                          "Skróty",
    SHORTCUTS_HINT:                     "Oddziel klawisze myślnikiem, na przykład: Ctrl-Alt-G<br>Możesz użyć angielskich identyfikatorów klawiszy Ctrl, Cmd (Mac), Alt i Shift.",
    SHOWN_DATE_FORMAT:                  "Format dat commit'ów w historii",
    SHOW_BASH_TERMINAL_BUTTON:          "Pokaż przycisk Bash/Terminal na panelu",
    SHOW_TERMINAL_IN_TOOLBAR:           "Pokaż ikonę Terminala na pasku narzędziowym",
    SHOW_UNTRACKED:                     "Pokaż untracked",
    STRIP_WHITESPACE_FROM_COMMITS:      "Pozbądź się końcowych białych znaków z commit'ów",
    TARGET_BRANCH:                      "Target branch",
    TERMINAL_DISABLED:                  "Konsola Bash/Terminal jest wyłączona, ponieważ nie znaleziono właściwego pliku wykonywalnego",
    TITLE_CHECKOUT:                     "Na pewno chcesz checkout tego commita?",
    TITLE_RESET:                        "Na pewno chcesz resetować?",
    TOOLTIP_CHECKOUT_COMMIT:            "Checkout konkretnego commita",
    TOOLTIP_CLONE:                      "Klonuj istniejące repozytorium",
    TOOLTIP_CLOSE_NOT_MODIFIED:         "Zamknij pliki niemodyfikowane z Git [Shift-click, aby otworzyć ponownie zmodyfikowane pliki]",
    TOOLTIP_COMMIT:                     "Commituj wybrane pliki",
    TOOLTIP_FETCH:                      "Fetch wszystkich remotes i refresh counters",
    TOOLTIP_FIND_CONFLICTS:             "Zaczyna poszukiwania konfilktów Git merge/rebase w projekcie",
    TOOLTIP_GITPUSH:                    "Git-FTP Push",
    TOOLTIP_HIDE_FILE_HISTORY:          "Ukryj historię pliku",
    TOOLTIP_HIDE_HISTORY:               "Ukryj historię",
    TOOLTIP_INIT:                       "Inicjalizuj repozytorium",
    TOOLTIP_MERGE_ABORT:                "Przerwij operację mergowania i resetuj HEAD do ostatniego lokalnego commita",
    TOOLTIP_MORE:                       "Więcej akcji\u2026",
    TOOLTIP_OPEN_BASH:                  "Otwórz konsolę Bash/Terminal",
    TOOLTIP_PICK_REMOTE:                "Wybierz preferowany remote",
    TOOLTIP_PULL:                       "Git Pull",
    TOOLTIP_PUSH:                       "Git Push",
    TOOLTIP_REBASE_ABORT:               "Przerwij operację rebase i resetuj HEAD do oryginalnego brancha",
    TOOLTIP_REBASE_CONTINUE:            "Restartuj proces rebasing'u po rozwiązaniu konfliktu z merge",
    TOOLTIP_REBASE_SKIP:                "Restartuj proces rebasing'u przez pominięcie aktualnego patcha",
    TOOLTIP_REFRESH_PANEL:              "Odśwież panel",
    TOOLTIP_SHOW_FILE_HISTORY:          "Pokaż historię pliku",
    TOOLTIP_SHOW_HISTORY:               "Pokaż historię",
    UNDO_CHANGES:                       "Porzuć zmiany",
    UNDO_LAST_LOCAL_COMMIT:             "Confij ostatni lokalny (nie push'owany) commit",
    URL:                                "URL",
    USERNAME:                           "Nazwa użytkownika",
    USER_ABORTED:                       "Użytkownik przerwał!",
    USER_DATE_FORMAT:                   "(<a href='http://momentjs.com/docs/#/displaying/format/'>Składnia</a>) własnego formatu daty",
    USE_CODE_INSPECTION:                "Użyj inspekcji kodu",
    USE_GITFTP:                         "Użyj Git-FTP",
    USE_GIT_GUTTER:                     "Użyj zaznaczenia na marginesie",
    USE_NOFF:                           "Utwórz merge commit nawet wtedy, gdy merge rozwiązywany jest jako fast-forward (--no-ff)",
    USE_REBASE:                         "Użyj REBASE",
    USE_VERBOSE_DIFF:                   "Pokaż rozwklekłe wyjście w diff'ach",
    USE_DIFFTOOL:                       "Użyj difftool dla diff'ów",
    USING_GIT_VERSION:                  "Wersja Gita",
    VIEW_AUTHORS_FILE:                  "Pokaż autorów pliku",
    VIEW_AUTHORS_SELECTION:             "Pokaż autorów zaznaczenia",
    VIEW_THIS_FILE:                     "Pokaż ten plik",
    TAG_NAME_PLACEHOLDER:               "Wpisz nazwę tagu tutaj\u2026",
    TAG_NAME:                           "Tag"
});
